(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'),modal=$('#modal'),address=$('#address'),sitePanel=$('#sitePanel'),toastEl=$('#toast');
const STORE='rainforest_end_v6';
const base={sound:false,visited:['chat','portal','wild','search','notes'],channel:'coord',notes:'',glyphNotes:{},openedPhotos:[],searchHistory:[],gis:{t:44,rain:false,contour:true,drone:false,zoom:1,tx:0,ty:0,selected:[],compared:false},flash:{x:2,y:8,gate:false},e:{},submitted:false};
let st=load();
function load(){try{return Object.assign(structuredClone(base),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return structuredClone(base)}}
function save(){localStorage.setItem(STORE,JSON.stringify(st))}
function e(k,v=true){st.e[k]=v;save();updateChrome();derive()}
function has(k){return !!st.e[k]}
function route(){return (location.hash.slice(1)||'chat').split('?')[0]}
function param(k){return new URLSearchParams(location.hash.split('?')[1]||'').get(k)}
function go(r){location.hash='#'+r}
function visit(r){if(!st.visited.includes(r)){st.visited.push(r);save()}}
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),1700)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const ADDR={chat:'fieldtalk.local/workspace/azera',portal:'azera-rainforest.org/season-2026',wild:'wildtrace.app/u/zhou-ye',map:'atlas.azera-research.org/UL09',cloud:'cloudline.app/shared/zhouye-field',search:'echosearch.example/search',medical:'docs.azera-research.org/medical-log',drone:'survey.azera-research.org/review/0922',flash:'linxian.neocities.example/game',notes:'local://field-notes',article:'archive.example/document',rescue:'sar.gov/azera/supplement',ending:'sar.gov/azera/bulletin'};
function derive(){
 const routeA=has('track_offset')&&has('rain_window');
 const routeB=has('track_offset')&&has('chat_route_change');
 const routeC=has('drone_oldriver')&&has('chat_route_change');
 st.e.route_resolved=routeA||routeB||routeC;
 st.e.contact_resolved=(has('chat_contact')&&has('cloud_village'))||(has('chat_contact')&&has('drone_village'))||(has('cloud_village')&&has('camera_match'));
 st.e.ritual_resolved=[has('medical_comment'),has('fieldnote_read'),has('glyph_context'),has('flash_gate')].filter(Boolean).length>=3;
 st.e.log_ready=st.e.route_resolved&&st.e.contact_resolved&&st.e.ritual_resolved&&has('painter_read');
 st.e.final_ready=has('last_log')&&st.e.route_resolved&&(has('drone_village')||has('drone_oldriver'));
 if(st.e.route_resolved&&st.e.contact_resolved){visit('drone');visit('medical')}
 if(st.e.log_ready)st.e.log_available=true;
 if(st.e.final_ready)visit('rescue');save();updateChrome();
}
function pollution(){return st.e.final_ready?3:st.e.ritual_resolved?2:st.e.contact_resolved?1:0}
function updateChrome(){document.body.className=`page-${route()} p${pollution()}`;address.textContent=ADDR[route()]||'local://'+route();$('#sound').textContent='环境声：'+(st.sound?'开':'关')}
window.addEventListener('hashchange',render);$('#back').onclick=()=>history.back();$('#home').onclick=()=>go('chat');$('#notes').onclick=()=>go('notes');
const sites=[['chat','FieldTalk','项目沟通'],['portal','联合项目官网','公开研究资料'],['wild','WildTrace','周野的户外账号'],['search','EchoSearch','公开互联网检索'],['notes','本地笔记','自己的记录'],['map','Azera Atlas','GIS会话'],['cloud','Cloudline','共享照片'],['medical','现场医疗表','在线记录'],['drone','Survey Review','无人机预览'],['flash','林线之外','2011旧网页'],['rescue','搜救补充材料','应急管理部门']];
$('#sites').onclick=()=>{sitePanel.hidden=!sitePanel.hidden;if(!sitePanel.hidden){sitePanel.className='panel';sitePanel.innerHTML=sites.filter(x=>st.visited.includes(x[0])).map(x=>`<button class="site-link" data-go="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('');$$('[data-go]').forEach(b=>b.onclick=()=>{sitePanel.hidden=true;go(b.dataset.go)})}};
let aud=null;$('#sound').onclick=()=>{st.sound=!st.sound;save();audioScene();updateChrome()};
function audioScene(){if(!st.sound){if(aud){aud.pause();aud=null}return}const r=route(),file=r==='map'?'river.wav':r==='drone'?'drone.wav':r==='flash'?'crt.wav':['portal','wild','cloud','article','ending'].includes(r)?'jungle.wav':'room.wav';if(!aud||!aud.src.endsWith(file)){if(aud)aud.pause();aud=new Audio('assets/audio/'+file);aud.loop=true;aud.volume=.28;aud.play().catch(()=>{})}}

/* glyphs */
const GL={eye:['M9 24Q24 8 39 24Q24 40 9 24','M19 24a5 5 0 1 0 10 0a5 5 0 1 0-10 0'],mouth:['M10 18Q24 12 38 18','M10 30Q24 36 38 30','M18 24h12'],body:['M15 8Q10 24 15 40','M33 8Q38 24 33 40','M15 16Q24 22 33 16','M15 32Q24 26 33 32'],road:['M10 7Q33 15 18 25Q8 34 38 41'],river:['M12 6Q36 14 13 24Q35 34 12 42','M23 7Q40 17 24 27Q10 36 37 42'],rain:['M10 13h28','M15 19l-3 9','M24 19l-3 12','M33 19l-3 9'],return:['M36 10Q10 12 14 28Q18 41 36 34','M31 29l5 5-6 4'],home:['M9 18L24 8l15 10v21H9z','M18 39V27h12v12'],outside:['M10 10h28v28H10z','M5 24h14','M29 24h14'],night:['M13 10Q34 14 30 34Q17 42 12 28Q26 31 28 15'],fire:['M24 7Q13 20 20 27Q27 33 18 41','M27 13Q38 25 29 41'],bone:['M15 12Q10 8 8 13Q10 18 16 16l16 16Q38 35 40 30Q39 24 33 25L17 11'],name:['M12 13h17Q37 13 34 22Q31 30 18 30','M18 30v10','M13 40h16'],dream:['M10 26Q16 9 25 17Q33 24 38 11','M11 34Q22 26 37 36','M20 7v6'],elder:['M24 9v30','M12 17h24','M15 30Q24 23 33 30'],child:['M24 10v27','M15 19Q24 12 33 19','M16 31Q24 38 32 31'],hand:['M16 36V21','M16 22l-6-7','M16 22l-2-11','M16 22l4-10','M16 22l9-7','M16 30l15-6'],salt:['M12 14h24','M10 25h28','M14 36h20','M18 9v31','M30 9v31']};
const GKEY=Object.keys(GL);function glyph(name){return `<span class="glyph"><svg viewBox="0 0 48 48"><g fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${GL[name].map(p=>`<path d="${p}"/>`).join('')}<path d="M20 4h8" stroke="#92281f" stroke-width="3"/></g></svg></span>`}

/* data */
const CH={
coord:[
['09/24 08:12','罗岚','六人科考队已经超过通信窗口。当地搜救、大学和保险方都已启动联络。你原本在项目邀请名单里，所以访客权限还在。不要自己进山。',''],
['09/24 08:13','系统','已建立事故编号 EM-2026-0924-ARZ；保险方回执将单独归档。',''],
['09/24 08:15','罗岚','今天11点前还有一次直升机窗口，但云底可能不够。地面队已经从河口出发。',''],
['09/24 08:16','罗岚','北段两个预定营位都没发现完整营地。河水还在涨，现场队现在只缺一件事：他们离开原路线后究竟去了哪一侧。',''],
['09/24 08:17','罗岚','卫星服务商正在重放09/22晚间缓存。对方只保证文字，图像按优先级恢复。',''],
['09/24 08:18','系统','天气：乌伦上游 24h累计降雨 86mm；河口水位 +0.74m。',''],
['09/24 08:19','罗岚','项目门户保留原计划、许可和成员信息。现场公开频道是只读。','portal'],
['09/24 08:23','罗岚','卫星箱先传文字，再传低清预览，附件延迟可能数小时。时间对不上时看拍摄时间，不要看同步时间。',''],
['09/24 08:24','系统','家属联络已移交学校危机响应办公室。',''],
['09/24 08:25','罗岚','保险方要成员护照号，我已经从项目行政那边拿，不需要你处理。',''],
['09/24 08:26','罗岚','地方社区办公室提醒：上游有季节采集家庭，现场队不要把任何居民点先标成危险目标。',''],
['09/24 08:31','系统','访客权限更新：#现场公开频道、#后勤与装备、#生物记录、#影像与无人机。',''],
['09/24 08:34','系统','直升机任务 #H2 暂停：云底低于最低进场标准。',''],
['09/24 08:47','罗岚','学校法务确认你可以查看周野主动共享给你的材料，但不要转发公开。',''],
['09/24 09:02','罗岚','家属在问是否还能确认最后可信位置。任何判断都要能被现场队复核。',''],
['09/24 09:08','系统','搜救队回报：北段营位B发现旧篝火，不确认与科考队有关。',''],
['09/24 09:14','罗岚','篝火先别算证据。那条线是公开徒步线，过去两周有人走过。','']
],
zhou:[
['09/18 19:14','周野','你真赶不上？车明早六点从中转站走。',''],
['09/18 19:16','你','航司说至少延五小时。落地再看。',''],
['09/18 19:18','周野','别硬追。雨季夜路更不值。下个补给周期也能进。',''],
['09/18 19:21','周野','项目页账号给你开了。路线别用我昨天那版，今天又改了河滩绕行。','portal'],
['09/18 23:07','周野','云盘还是原共享目录。原图太大，卫星箱每天先推低清和文字。','cloud'],
['09/19 00:11','周野','我这几天在看一个十几年前的破网页游戏，叫“林线之外”。里面河弯和乌伦上游像得过头。回来给你讲。',''],
['09/19 05:56','周野','上车了。你先睡。回来请你喝酒。',''],
['09/21 18:42','周野','陈栩飞完说西边有炊烟。王老师觉得是季节猎棚。雨再小一点明天去确认。',''],
['09/22 00:37','周野','共享刚推了一批。别吐槽压缩，卫星箱今天只有两百多K。','cloud']
],
field:[
['09/19 07:08','许放','过检查站。后面手机信号基本没了，统一走卫星箱。文字优先。',''],
['09/19 18:22','林澈','所有人脚踝检查一下。蚂蟥咬口别用火烫，第三遍。',''],
['09/20 10:13','王敬山','东岸叫声不是长臂猿，频率不对。下午再布两个录音点。',''],
['09/20 16:50','高桥','下游船夫说第三支流“里面有人”，但不肯解释。也可能只是季节采集点。',''],
['09/21 08:03','许放','昨晚河涨得快。北段如果继续涨，明天可能要改路线。','map'],
['09/21 13:28','陈栩','西边飞完，有规则屋顶，不像临时棚。低清预览今晚排队。',''],
['09/21 19:51','周野','四个人来营地换盐和干鱼。没有武器。旧电池盒像十年前的型号。',''],
['09/21 20:14','高桥','他们把上游说成“amokha”或接近这个音。不确定是地名、群体还是别的。',''],
['09/22 07:42','许放','北段水位比昨晚高。先沿第三支流西南绕半天，看能不能接旧河床。','map'],
['09/22 12:05','林澈','王老师和许放都恶心。先停那锅汤，喝封装水。','medical'],
['09/22 17:36','周野','那个旧相机不是我们的。陈栩确认过。','cloud'],
['09/22 20:08','高桥','木屋墙面和路边刻痕有重复结构。先不要翻译，拍原位和相邻物件。','cloud'],
['09/23 00:41','陈栩','无人机电池只剩一块。白天拍到旧河槽附近有人把东西塞进石缝。','']
],
gear:[['09/19 07:20','许放','卫星箱主机 / 两块电池 / 备用滤芯已签出。',''],['09/20 21:12','陈栩','无人机3号电机进沙，明早拆。',''],['09/21 18:03','林澈','退热药余14片，补液盐18包。',''],['09/22 06:19','许放','GPSMAP 67i 昨夜漂了两个点，重启后正常。',''],['09/22 18:40','陈栩','旧相机没有电池，机身序列看不清。','cloud']],
bio:[['09/19 17:05','王敬山','第一录音点：蝉声过强，弃。',''],['09/20 05:31','林澈','河边发现三趾足迹，尺寸不像鹿。',''],['09/20 22:44','王敬山','夜行叫声 2.8kHz 附近有稳定重复，先标“未知灵长类”。',''],['09/21 09:16','高桥','上游有人把同一种树皮编成束，可能是采集标记。',''],['09/22 15:04','王敬山','今天没有继续录音。所有人状态不太好。','medical']],
drone:[['09/20 14:24','陈栩','河谷正射没拼完，云层太低。',''],['09/21 13:31','陈栩','西侧屋顶约8—12处，坐标已写入飞行备注。',''],['09/21 16:02','周野','你把那张旧河槽也留着，GIS里的蓝线像偏了。','map'],['09/22 13:33','陈栩','中央空地地面有重复几何标记。不是田界。',''],['09/23 00:43','系统','DJI_0508 低清代理排入卫星同步队列。','']]
};
function renderChat(){visit('chat');const c=st.channel;let rows=[...(CH[c]||CH.coord)];if(c==='coord'&&has('route_resolved')&&has('contact_resolved'))rows.push(['今天 16:04','罗岚','你标出的路线偏移和现场接触记录能互相对应。陈栩的无人机低清预览刚从卫星箱恢复。','drone']);if(c==='coord'&&has('log_available'))rows.push(['今天 17:02','罗岚','卫星箱恢复了一段未完成上传的本地文本，创建者是周野。项目方已允许查看。','lastlog']);if(c==='coord'&&has('final_ready'))rows.push(['今天 17:26','罗岚','搜救补充材料入口仍开着。现场只接受可以复核的坐标、路线依据和风险说明。','rescue']);app.innerHTML=`<section class="ft"><aside class="ft-rail"><div class="ft-logo">FT</div><div class="workspace active">AZ</div><div class="workspace">+</div></aside><nav class="ft-side"><h1>阿泽拉联合项目</h1><div class="ft-search">搜索消息、人员或文件…</div><div class="ft-section">协作</div>${[['coord',has('log_available')||has('final_ready')?'● 罗岚 · 后方协调':'罗岚 · 后方协调'],['zhou','周野'],['field','# 现场公开频道'],['gear','# 后勤与装备'],['bio','# 生物记录'],['drone','# 影像与无人机']].map(x=>`<button class="channel ${c===x[0]?'active':''}" data-ch="${x[0]}">${x[1]}</button>`).join('')}<div class="ft-section">成员</div>${['周野','林澈','陈栩','高桥健','许放','王敬山'].map((n,i)=>`<button class="channel" data-person="${n}">● ${n}${i<2?' · 离线':''}</button>`).join('')}</nav><div class="ft-main-wrap"><main class="ft-main"><header class="ft-head"><h2>${c==='coord'?'罗岚 · 后方协调':c==='zhou'?'周野':c==='field'?'# 现场公开频道':c==='gear'?'# 后勤与装备':c==='bio'?'# 生物记录':'# 影像与无人机'}</h2><small>只读归档</small><span class="membercount">12 成员</span></header><div class="stream"><div class="dayline"><span>2026年9月</span></div>${rows.map((m,i)=>msgHTML(m,i)).join('')}${pollution()>=2&&c==='coord'?`<div class="typing">周野 正在输入…</div>`:''}</div><footer class="composer"><div>此频道已归档；访客不能发送消息。</div></footer></main><aside class="thread" hidden><button id="threadClose">×</button><h3>回复线程</h3><div id="threadBody"></div></aside></div></section>`;
$$('[data-ch]').forEach(b=>b.onclick=()=>{st.channel=b.dataset.ch;save();if(st.channel==='field')e('chat_contact');if(st.channel==='field')e('chat_route_change');renderChat()});$$('[data-link]').forEach(b=>b.onclick=()=>openLink(b.dataset.link));$$('[data-thread]').forEach(b=>b.onclick=()=>{const th=$('.thread');th.hidden=false;$('#threadBody').innerHTML=`<p><b>林澈</b>：如果是改线，最好把水位和GPS一起看。</p><p><b>陈栩</b>：西侧飞行里能看到旧河槽，但不是每个时段都清楚。</p>`;$('#threadClose').onclick=()=>th.hidden=true});$$('[data-person]').forEach(b=>b.onclick=()=>toast(`${b.dataset.person} · 项目成员资料仅显示公开字段`));}
function msgHTML(m,i){const [t,n,text,link]=m;return `${i===4?'<div class="systemmsg">— 卫星同步批次 #A24-091 已完成 —</div>':''}<article class="msg"><div class="avatar">${n.slice(0,1)}</div><div><div><span class="name">${n}</span><span class="time">${t}</span></div><p>${text}</p>${link?`<div class="attach"><span>${link==='portal'?'项目门户.pdf':link==='map'?'UL09_路线会话':link==='cloud'?'共享目录':link==='medical'?'medical_log.xlsx':link==='drone'?'DJI低清代理':'资料'}</span><button data-link="${link}">打开</button></div>`:''}${i%5===1?'<div class="reacts">👍 3　👀 2　<span data-thread style="text-decoration:underline;cursor:pointer">2条回复</span></div>':''}</div></article>`}
function openLink(l){if(l==='lastlog')location.hash='#article?id=lastlog';else{visit(l);go(l)}}

function renderPortal(){visit('portal');app.innerHTML=`<section class="portal"><div class="hero"><img src="assets/photos/aerial_river.webp"><div class="hero-brand">AZERA RAINFOREST COOPERATIVE RESEARCH PROGRAM · 2026</div><nav class="hero-nav"><span>项目介绍</span><span>研究日志</span><span>公开数据</span><span>团队</span></nav><div class="hero-copy"><div class="kicker">FIELD SEASON 2026 / ULEN UPPER BASIN</div><h1>乌伦河上游<br>跨学科联合野外季</h1><p>雨林大学、人类学研究中心与阿泽拉自然史博物馆联合开展的跨学科项目。研究目标包括夜行灵长类声学记录、支流水文测绘、植物群落样方与季节性人类活动调查。</p></div></div><div class="portal-index">
<div class="portal-grid"><div><h2>研究范围</h2><p>本野外季覆盖乌伦河上游约188平方公里，主要调查窗口为9月18日至10月5日。项目以公开研究、许可采样和低干扰观察为原则，不进入地方政府标记的宗教场所与争议土地。</p><ul><li>夜行灵长类声学样本</li><li>河道断面与降雨记录</li><li>植被样方与真菌记录</li><li>季节采集点观察</li><li>旧路线复测</li><li>社区口述访谈</li></ul></div><div class="meta">研究许可 ARA-26-UL09<br>伦理审查 HREC-2026-144<br>野外保险 AEG-822194<br>卫星终端登记 6台<br>无人机任务许可 D-2026-0918<br><br>合作机构<br>阿泽拉大学地理系<br>雨林大学生物声学实验室<br>国家自然史博物馆<br>乌伦县社区合作办公室</div></div>
<div class="portal-grid"><figure><img src="assets/photos/camp_river.webp"></figure><div><h2>方法与数据</h2><p>GPS轨迹每五分钟记录一次。暴雨时段可能因峡谷遮挡出现短时漂移，因此任何路线结论都要求与降雨、无人机、通信或人工日志交叉验证。</p><table class="research-table"><tr><th>数据集</th><th>频率</th><th>公开状态</th></tr><tr><td>UL09 GPS轨迹</td><td>5 min</td><td>延迟公开</td></tr><tr><td>自动录音</td><td>连续</td><td>物种审校后</td></tr><tr><td>降雨</td><td>15 min</td><td>公开</td></tr><tr><td>无人机正射</td><td>任务制</td><td>限制</td></tr><tr><td>医疗日志</td><td>事件制</td><td>内部</td></tr></table></div></div>
<div class="portal-grid"><div><h2>过去野外季</h2><p>项目并非第一次进入阿泽拉地区。公开档案中保留2019、2021、2023三个野外季的报告，内容大多与本次失联无关。</p><div class="downloads">${[['2019鸟类迁徙摘要','PDF · 8.1MB'],['2021河道侵蚀数据','CSV · 3.6MB'],['2023植物样方图集','ZIP · 411MB'],['野外伦理手册','PDF · 1.2MB'],['社区语言转写规范','PDF · 4.8MB'],['2026设备清单','XLSX · 86KB']].map(x=>`<div class="download"><b>${x[0]}</b><small>${x[1]}<br>公开资料</small></div>`).join('')}</div></div><div class="meta"><b>成员</b><br><br>周野 / 野外记录<br>林澈 / 队医<br>陈栩 / 影像与无人机<br>高桥健 / 语言与民俗<br>许放 / 领队<br>王敬山 / 生物声学<br><br><b>公开联系人</b><br>field-office@azera-research.org<br>+00 412 776 910</div></div>
<div class="status-strip"><div><b>最后计划位置</b><span>09/22 · UL-09北段第三支流</span></div><div><b>现场通信</b><span>09/23 02:41 后无完整上传</span></div><div><b>本地搜救</b><span>已启动 / 北段两个预定营位已查</span></div><div><b>数据同步</b><span>低带宽缓存仍在恢复</span></div></div></div></section>`;}

const posts=[
['2026.09.18','机场','没赶上。机械故障。周野发来一句“别硬追”。'],['2026.09.11','广州→阿泽拉','出发前最后一次装备检查。没带新炉头，怕又坏。'],['2026.07.02','加里曼丹','42km，两天全是雨。周野把袜子烤焦了。'],['2026.05.17','岭北山脊','我们又走回了2021那条线。天气好得不像同一座山。'],['2025.12.04','城郊夜跑','只是下班后跑了8km。没有故事。'],['2025.08.19','西岭','林线以上风太大，提前撤。'],['2024.11.16','乌伦上游·第三支流','以前只到过河口。再往里没有公开轨迹。'],['2024.04.03','加里曼丹','今天认识了一个叫Eru的老人——不是那个Eru，重名。笑死。'],['2023.10.08','川西','高反，走了11km就下撤。'],['2023.03.21','南坡','第一次用67i，电池比预想耐。'],['2022.12.31','城市','今年最后一天没爬山，吃火锅。'],['2022.06.07','竹岭','某人又忘带地钉。'],['2021.08.19','帽山','走在云里，突然觉得人类的记忆好脆弱。'],['2021.07.30','帽山','帐篷搭反。不是我。'],['2020.10.02','虎峡','摔伤，缝了六针。'],['2020.01.01','城市','今年想少买装备。失败。'],['2019.11.23','乌伦河口','第一次来阿泽拉。只走公开步道。'],['2019.06.14','城北','第一次和周野一起露营。雨下了一夜。']];
function renderWild(){visit('wild');app.innerHTML=`<section class="wild"><div class="wild-top"><img src="assets/photos/mist_ridge.webp"><div class="wild-nav"><b>WildTrace</b>探索　路线　社区　装备　活动</div><div class="wild-profile"><img src="assets/photos/zhou_profile.webp"><div><h1>周野 <small style="font-size:13px">Ye Zhou</small></h1><p>山不会消失，照片也会过期。</p></div><div class="stats"><div><b>132</b><small>动态</small></div><div><b>48</b><small>路线</small></div><div><b>2.4k</b><small>粉丝</small></div></div></div></div><div class="wild-layout"><aside class="years">${[2026,2025,2024,2023,2022,2021,2020,2019].map(y=>`<button>${y}</button>`).join('')}</aside><main class="feed">${posts.map((p,i)=>`<article class="post" data-year="${p[0].slice(0,4)}"><time>${p[0]}</time><div><h2>${p[1]}</h2><p>${p[2]}</p><div class="meta">♡ ${12+i*3}　评论 ${i%7}　公开</div></div></article>`).join('')}</main><aside class="wild-side"><h3>常用装备</h3><ul><li>GPSMAP 67i · 2023至今</li><li>Sony RX100 VII · 2024至今</li><li>65L背包 · 修补过3次</li><li>轻量炉头 · 2022至今</li></ul><h3 style="margin-top:30px">收藏路线</h3><ul><li>乌伦河公开步道</li><li>帽山旧林道</li><li>西岭北脊</li><li>虎峡穿越线</li></ul></aside></div></section>`;$$('.years button').forEach(b=>b.onclick=()=>{const el=document.querySelector(`.post[data-year="${b.textContent.trim()}"]`);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})});}

const pts=[[19,20,'09/21 06:00',376],[25,29,'09/21 12:00',382],[31,38,'09/21 18:00',394],[38,50,'09/22 00:00',405],[48,57,'09/22 06:00',414],[59,61,'09/22 12:00',429],[69,67,'09/22 17:43',443],[79,74,'09/22 23:00',458]];
function renderMap(){visit('map');const g=st.gis;app.innerHTML=`<section class="gis"><div class="mapstage"><div class="mapworld" id="mapworld" style="transform:translate(${g.tx}px,${g.ty}px) scale(${g.zoom})"><img class="base" src="assets/maps/ulen_topo.webp">${g.rain?'<img class="rain" src="assets/maps/rain_overlay.webp">':''}<svg class="tracksvg" viewBox="0 0 100 100" preserveAspectRatio="none"><path class="planned" d="M18 18 C32 30,48 42,78 62"/><path class="actual" d="M19 20 L25 29 L31 38 L38 50 L48 57 L59 61 L69 67 L79 74"/>${g.drone?'<path class="oldriver" d="M42 58 C52 67,63 72,80 82"/>':''}${pts.map((p,i)=>`<circle class="trackpt" data-pt="${i}" cx="${p[0]}" cy="${p[1]}" r=".46"/>`).join('')}${g.compared?'<line class="measureline" x1="48" y1="57" x2="62" y2="51"/>':''}</svg></div></div><div class="gis-tools"><button id="zin">＋</button><button id="zout">−</button><button id="resetmap">⌖</button></div><aside class="layerpanel"><h3>LAYERS / UL-09</h3><label><input checked disabled type="checkbox"> GPS轨迹（队伍）</label><label><input id="rainLayer" ${g.rain?'checked':''} type="checkbox"> 累计降雨</label><label><input checked disabled type="checkbox"> 等高线（40m）</label><label><input id="droneLayer" ${g.drone?'checked':''} type="checkbox"> 无人机旧河槽标注</label><label class="${pollution()>=3?'ghost-layer':''}"><input type="checkbox" disabled ${pollution()>=3?'checked':''}> 地方采集路径</label></aside><aside class="readout"><h2>轨迹 UL-09</h2><dl><dt>计划路线</dt><dd>北段 / 第三支流东岸</dd><dt>记录间隔</dt><dd>5 min</dd><dt>最后完整点</dt><dd>09/22 17:43</dd><dt>设备</dt><dd>GPSMAP 67i</dd><dt>当前时间</dt><dd id="maptime">${timeFromSlider(g.t)}</dd></dl><p id="readtext">选择轨迹点查看位置、高程、时间与记录精度。</p></aside><div class="timeline"><div class="ticks"><span>09/21 06:00</span><span>09/22</span><span>09/23 06:00</span></div><input id="timeslider" type="range" min="0" max="100" value="${g.t}"></div><div class="mapcoords" id="mapcoords">2.4175 N · 114.2260 E　EPSG:4326</div><div class="north">N ↑</div><div class="scalebar"><i></i>1 km</div><div class="analysisbar"><button id="compare">比较计划线 / 当前轨迹</button></div><div class="pointtip" id="pointtip" hidden></div></section>`;
$('#zin').onclick=()=>{g.zoom=Math.min(1.8,g.zoom+.15);save();renderMap()};$('#zout').onclick=()=>{g.zoom=Math.max(.8,g.zoom-.15);save();renderMap()};$('#resetmap').onclick=()=>{Object.assign(g,{zoom:1,tx:0,ty:0});save();renderMap()};$('#rainLayer').onchange=ev=>{g.rain=ev.target.checked;if(g.rain&&g.t>=45&&g.t<=78)e('rain_window');save();renderMap()};$('#droneLayer').onchange=ev=>{g.drone=ev.target.checked;save();renderMap()};$('#timeslider').oninput=ev=>{g.t=+ev.target.value;$('#maptime').textContent=timeFromSlider(g.t);if(g.rain&&g.t>=45&&g.t<=78)e('rain_window');save()};$('#compare').onclick=()=>{g.compared=true;e('track_offset');save();renderMap();toast('已显示计划线与轨迹之间的横向距离')};$$('[data-pt]').forEach(c=>c.onclick=ev=>{const p=pts[+c.dataset.pt];const tt=$('#pointtip');tt.hidden=false;tt.style.left=(ev.clientX+12)+'px';tt.style.top=(ev.clientY-30)+'px';tt.innerHTML=`${p[2]}<br>高程 ${p[3]}m<br>GPS精度 ±${4+(+c.dataset.pt%4)*3}m`;g.selected.push(+c.dataset.pt);g.selected=[...new Set(g.selected)].slice(-4);save()});const stage=$('.mapstage'),world=$('#mapworld');let drag=null;stage.onpointerdown=ev=>{if(ev.target.closest('button,input,.trackpt,.layerpanel,.readout,.timeline,.analysisbar'))return;drag={x:ev.clientX,y:ev.clientY,tx:g.tx,ty:g.ty};stage.setPointerCapture(ev.pointerId)};stage.onpointermove=ev=>{const r=stage.getBoundingClientRect();const lon=114.18+(ev.clientX-r.left)/r.width*.09;const lat=2.46-(ev.clientY-r.top)/r.height*.09;const mc=$('#mapcoords');if(mc)mc.textContent=`${lat.toFixed(4)} N · ${lon.toFixed(4)} E　EPSG:4326`;if(!drag)return;g.tx=drag.tx+(ev.clientX-drag.x);g.ty=drag.ty+(ev.clientY-drag.y);world.style.transform=`translate(${g.tx}px,${g.ty}px) scale(${g.zoom})`};stage.onpointerup=()=>{drag=null;save()};}
function timeFromSlider(v){const h=6+Math.round(v/100*48),d=21+Math.floor(h/24),hh=h%24;return `09/${String(d).padStart(2,'0')} ${String(hh).padStart(2,'0')}:00`}

const photos=[['camp_dinner.webp','09/19 19:42','IMG_3011.JPG','手机','河滩营地晚饭'],['normal_extra_2.webp','09/19 20:08','IMG_3016.JPG','手机','晾晒衣物'],['normal_extra_3.webp','09/20 06:52','IMG_3038.JPG','手机','晨间记录'],['wet_gear.webp','09/20 07:18','IMG_3042.JPG','手机','雨后晾晒'],['field_notebook.webp','09/20 10:36','IMG_3051.JPG','手机','记录本与GPS'],['normal_extra_4.webp','09/20 14:48','IMG_3065.JPG','手机','过河前自拍'],['group_river.webp','09/20 15:06','IMG_3068.JPG','手机','过河记录'],['normal_extra_5.webp','09/21 08:12','IMG_3077.JPG','无人机代理','河谷概览'],['normal_extra_6.webp','09/21 13:07','IMG_3089.JPG','手机','无人机起飞'],['normal_extra_7.webp','09/21 16:55','IMG_3108.JPG','手机','西侧山脊'],['night_gear.webp','09/21 23:08','IMG_3132.JPG','手机','夜间装备'],['old_tree_gear.webp','09/22 16:03','IMG_3178.JPG','Sony RX100','树上的旧设备'],['classroom_wall.webp','09/22 18:11','IMG_3192.JPG','Sony RX100','木屋内墙'],['ritual_platform.webp','09/22 19:27','IMG_3206.JPG','Sony RX100','中央空地'],['masked_night.webp','09/22 23:14','IMG_3221.JPG','手机','夜间林缘'],['old_expedition_photo.webp','09/23 00:09','IMG_3229.JPG','手机','旧照片翻拍']];
function renderCloud(){visit('cloud');const extra=pollution()>=2?1:0;app.innerHTML=`<section class="cloud"><header class="cloudbar"><b>Cloudline</b><span>${photos.length+extra} 项 · 2026年9月</span><input placeholder="搜索照片、地点或文件名"></header><div class="photo-flow">${photos.map((p,i)=>`<article class="photo" data-key="${(p[1]+' '+p[2]+' '+p[3]+' '+p[4]).toLowerCase()}"><button data-photo="${i}"><img src="assets/photos/${p[0]}"><time>${p[1]}</time></button></article>`).join('')}${extra?`<article class="photo"><button data-photo="ghost"><img src="assets/photos/subway_glyph.webp"><time>同步时间未知</time></button></article>`:''}</div></section>`;$$('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(b.dataset.photo));const ci=$('.cloudbar input');if(ci)ci.oninput=()=>{const q=ci.value.trim().toLowerCase();$$('.photo[data-key]').forEach(el=>el.style.display=!q||el.dataset.key.includes(q)?'':'none')};}
function openPhoto(id){let p;if(id==='ghost'){p=['subway_glyph.webp','--','IMG_0000.JPG','未知',''];e('ghost_photo')}else p=photos[+id];if(!st.openedPhotos.includes(String(id)))st.openedPhotos.push(String(id));if(+id===13)e('cloud_village');if(+id===11)e('camera_seen');if([12,13,15].includes(+id))e('glyph_context');save();modal.innerHTML=`<div class="modalbox"><button class="modalclose">×</button><div class="photo-viewer"><main><img src="assets/photos/${p[0]}"></main><aside class="photo-meta"><h2>${p[2]}</h2><dl><dt>拍摄时间</dt><dd>${p[1]}</dd><dt>设备</dt><dd>${p[3]}</dd><dt>同步</dt><dd>卫星箱低清批次</dd><dt>位置</dt><dd>${id==='11'?'1.6519N, 102.374E':'元数据保留'}</dd></dl>${id==='11'?'<p>机身侧面型号可读：Sony DSC-W220。序列末位被泥覆盖。</p>':''}${id==='12'?`<div>${glyph('child')}${glyph('name')}${glyph('home')}</div>`:''}${id==='13'?`<div>${glyph('body')}${glyph('elder')}${glyph('home')}</div>`:''}${id==='15'?`<div>${glyph('road')}${glyph('return')}</div>`:''}</aside></div></div>`;$('.modalclose').onclick=()=>modal.innerHTML='';}

const NOISE=[
['乌伦河皮划艇季节公告','ulen-kayak.example/notice','雨季支流不建议进入，水位每天16时更新。'],['阿泽拉旧桥维护计划','roads.azera.gov/ulen','北线两处便桥9月暂停车辆通行。'],['GPSMAP 67i 高湿环境用户讨论','wildtrace.community/thread/98211','峡谷和暴雨环境可能导致短时漂移，通常重启后恢复。'],['乌伦河流域地图命名变迁','geo-history.example/ulen-names','不同年代地图对第三支流和旧河槽使用不同名称。'],['夜行灵长类开放声学集','bioacoustics.example/nocturnal','公开样本可按频率和日期筛选。'],['旧网页镜像计划：户外个人站','web-archive.example/outdoors','2010—2012个人主页、Flash文件和留言簿镜像。'],['地方论坛：上游采木传闻','forum.example/ulen-logging','有人把夜间灯火解释为非法采木队；帖子没有提供坐标。'],['2017乌伦上游居民点调查','journal.example/ulen2017','作者结论“第三支流无永久居民点”，附录显示调查只覆盖河东岸。'],['地方小报：所谓“食人族”传闻','tabloid.example/jungle','使用夸张标题，仪式描述无可核来源。'],['社区办公室季节采集许可','county.example/forage','雨季允许登记家庭进入上游采集树脂与藤材。'],['阿泽拉机场雨季延误统计','traveldata.example/azera-air','9月支线航班平均延误2.6小时。'],['雨林真菌野外图鉴','mycology.example/azera','公众教育材料，与科考失联事件无直接关联。'],['乌伦县2025人口与季节迁移统计','stats.azera.gov/ulen','常住人口集中在河口，雨季仍有登记采集户短期上行。'],['阿泽拉大学野外急救培训','university.example/field-firstaid','课程资料：热病、脱水、蛇伤与食物污染。'],['2014第三支流水文站撤站说明','hydro.example/archive-2014','设备在连续洪水后迁至下游，旧站坐标仍被部分地图沿用。'],['乌伦河旧航拍图公开计划','geo-archive.example/ulen-aerial','1976、1998、2010三期航拍正在数字化。'],['摄影论坛：潮湿环境旧卡片机防潮','photo.example/tropical-camera','讨论干燥剂、电池仓腐蚀和W系列常见故障。'],['阿泽拉社区语言词表（公开版）','language.example/azera-basic','收录河口贸易语，不包含上游仪式词。'],['旧新闻纠错：2011搜救报道中的坐标误植','presswatch.example/ulen2011','指出两家报纸把河口坐标当作最后失联点。'],['志愿搜救论坛：雨林轨迹是否可信','sar-forum.example/gps-jungle','经验帖认为连续偏移比单点漂移更值得重视，但不能替代现场核验。'],['乌伦河徒步商业宣传页','travel.example/ulen-upper','把“无人区”作为营销词，实际线路只到第三支流河口。'],['地方电台节目文字稿：雨季里的上游居民','radio.example/ulen-seasonal','采访树脂采集家庭，受访者否认在更上游长期居住。'],['2018无人机测绘许可争议','localnews.example/drone-2018','社区曾因无人机飞越祭祀地投诉研究团队。'],['阿泽拉邮政旧地名索引','postal.example/oldnames','列出若干已停用村名和河段别称。'],['雨季露营锅具污染案例','fieldmed.example/case-pot','多人共同呕吐并不必然意味着毒素或传染病。'],['野外食物中毒快速判断表','fieldmed.example/foodborne','按潜伏期、共同进食史和水源暴露初筛。'],['2016非法采矿调查摘要','environment.example/mining-2016','调查区域位于乌伦河东侧，与第三支流西岸相距约40公里。'],['旧博客：我在乌伦河听见孩子唱歌','blog.example/ulen-voice','作者无坐标、无原始录音，评论区多年争论真假。']];
function results(q){const s=q.toLowerCase(),seed=[...s].reduce((a,c)=>a+c.charCodeAt(0),0)%NOISE.length;const rotated=[...NOISE.slice(seed),...NOISE.slice(0,seed)];const a=rotated.slice(0,10);if(/雨|水位|洪水/.test(s))a.unshift(['乌伦水位监测镜像','hydro.example/ulen-live','09/21至09/23水位连续上升，但上游雨量站有6小时缺测。']);if(/gps|轨迹|漂移/.test(s))a.unshift(['峡谷环境GPS误差测试','geo-lab.example/gps-canyon','单点误差可达数十米；持续同向偏移需要结合行进速度和地形判断。']);if(/w220|旧相机|sony/.test(s)){a.splice(2,0,['Sony DSC-W220 使用讨论','camera-forum.example/w220','2009年前后的卡片机，野外用户常在电池盖内写序列尾号。']);if(has('camera_seen'))a.splice(1,0,['2011乌伦上游三人失踪：装备清单补录','archive.news.example/2012-ulen','失踪摄影者冯祁携带银色 Sony DSC-W220，机身序列末四位 7134。','oldmissing'])}if(/2011|失踪.*乌伦|乌伦.*失踪/.test(s))a.unshift(['2011雨季三名徒步者在乌伦河上游失联','archive.news.example/2011-ulen','搜救21天后暂停。公开资料对“最后路线”存在两种版本。','oldmissing']);if(/amokha|阿摩|刻痕|符号/.test(s))a.unshift(['1978乌伦河上游田野笔记（节选）','anthro-archive.example/ulen78','未正式出版的工作笔记，记录身体、名字、河流与记忆的若干词形。','fieldnote']);if(/林线之外|line beyond|网页游戏/.test(s))a.unshift(['林线之外 / Beyond the Tree Line','linxian.neocities.example','2011年停止更新的个人网页游戏，作者同年失联。','flash']);if(/eru|sena|绘人|肖像|画家/.test(s)&&has('fieldnote_read'))a.unshift(['未归档附页：Eru的五张肖像','anthro-archive.example/ulen78-appendix','同一名女性被长期反复描绘，背面文字逐日缩短。','painter']);return a}
function renderSearch(){visit('search');const q=decodeURIComponent(param('q')||''),rs=q?results(q):[];app.innerHTML=`<section class="seek"><header class="seek-head"><span class="seek-brand">EchoSearch</span><input id="q" value="${esc(q)}" placeholder="搜索互联网"><div class="seek-tabs"><span>全部</span><span>新闻</span><span>图片</span><span>论坛</span><span>学术</span><span>文档</span></div></header><main class="seek-main">${q?`<div class="seek-count">约 ${8200+q.length*1973} 条结果 · 部分旧网页仅有镜像</div>${rs.map(r=>`<article class="result"><div class="url">${r[1]}</div><h2>${r[3]?`<button data-r="${r[3]}">${r[0]}</button>`:r[0]}</h2><p>${r[2]}</p></article>`).join('')}<div class="related">相关结果可能包含过期资料、二次转述和无法独立核实的说法。</div>`:'<div class="seek-count">搜索历史仅保存在本机。</div>'}</main></section>`;$('#q').onkeydown=ev=>{if(ev.key==='Enter'){const v=ev.target.value.trim();if(v){st.searchHistory.push(v);st.searchHistory=st.searchHistory.slice(-15);save();location.hash='#search?q='+encodeURIComponent(v)}}};$$('[data-r]').forEach(b=>b.onclick=()=>{if(b.dataset.r==='flash'){visit('flash');go('flash')}else location.hash='#article?id='+b.dataset.r});}

function renderMedical(){visit('medical');const rows=[['09/20','林澈','37.4','头痛、恶心','无用药','林中鸣水后更明显'],['09/20','高桥','36.8','疲惫、食欲下降','补液','可能与长时间潮湿有关'],['09/21','陈栩','38.1','发冷、肌肉酸痛','退热','采集血样'],['09/21','周野','37.1','轻微喉咙痛','无','持续观察'],['09/22','王敬山','38.4','恶心、反复呕吐','口服补液','午餐后约2h出现'],['09/22','许放','37.9','眩晕、厌恶气味','无','拒绝再次进食'],['09/22','高桥','38.3','高热、意识模糊','退热','批注线程'],['09/23','林澈','—','本人未记录','—','最后同步不完整']];app.innerHTML=`<section class="sheet"><div class="sheet-title">▦ <b>阿泽拉联合项目 — 现场医疗记录.xlsx</b>　<span style="color:#777">最后保存 09/23 01:17</span></div><div class="sheet-menu">文件 编辑 查看 插入 格式 数据 工具 帮助</div><div class="sheet-wrap"><table><thead><tr><th>#</th><th>日期</th><th>姓名</th><th>体温</th><th>症状</th><th>处理</th><th>备注</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+2}</td>${r.map((x,j)=>`<td class="${i>=4?'hot':''} ${i===6&&j===5?'comment':''}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="sheet-tabs"><button class="active">每日记录</button><button>症状统计</button><button>药品清单</button><button>检验结果</button></div><aside class="commentbox"><b>高桥 / D8 批注</b><p>我之前把 ${glyph('home')} + ${glyph('eye')} 当“守卫”。现在怀疑“内/家”表示归属，“眼”表示见证。不能据此单独翻译。</p><p>林澈回复：${glyph('mouth')} + ${glyph('body')} 也可能是“声音留在身体”，不一定是进食动作。</p><button id="medread">展开其余4条回复</button></aside></section>`;$('#medread').onclick=()=>{e('medical_comment');$('.commentbox').innerHTML+=`<p>高桥：同一个组合在儿童墙面和中央空地出现，但位置不同。我们需要更多上下文。</p><p>林澈：先别把身体症状和仪式联系起来，食物中毒仍然更可能。</p>`};$$('.sheet-tabs button').forEach((b,i)=>b.onclick=()=>{if(i===0)return;toast(['','统计表为空：样本量不足','药品盘点：退热药14片 / 补液盐18包','09/21血样未能完成现场检测'][i])})}

const droneFiles=[['DJI_0487_PROXY.JPG','09:04','drone_launch.webp'],['DJI_0490_PROXY.JPG','10:14','drone_village_1.webp'],['DJI_0497_PROXY.JPG','11:01','drone_village_2.webp'],['DJI_0508_PROXY.JPG','13:22','drone_village_3.webp']];
function renderDrone(){visit('drone');const idx=Math.max(0,Math.min(3,+param('f')||2)),f=droneFiles[idx];app.innerHTML=`<section class="drone"><aside class="d-files"><h2>飞行记录 / 09-22</h2>${droneFiles.map((x,i)=>`<button class="d-file ${i===idx?'active':''}" data-f="${i}">${x[0]}<br><small>${x[1]}</small></button>`).join('')}</aside><main class="d-stage"><img src="assets/photos/${f[2]}"><div class="scanbar"></div><div class="d-hud">UL-09 / LOW-RES STILL<br>2.4175N 114.226E</div><div class="d-time">RECORDED 2026-09-22 ${f[1]}　ALT ${312+idx*21}m</div></main><aside class="d-side"><h3>代理帧信息</h3><dl><dt>源文件</dt><dd>原视频仍在恢复队列</dd><dt>任务</dt><dd>支流西侧结构调查</dd><dt>定位</dt><dd>GPS ±7m</dd><dt>同步</dt><dd>09/24 15:42</dd></dl>${idx===2?'<button id="village">在GIS中标出屋顶范围</button>':''}${idx===3?'<button id="oldriver">在GIS中标出旧河槽</button>':''}</aside></section>`;$$('[data-f]').forEach(b=>b.onclick=()=>location.hash='#drone?f='+b.dataset.f);if($('#village'))$('#village').onclick=()=>{e('drone_village');st.gis.drone=true;save();toast('范围已发送到GIS临时图层')};if($('#oldriver'))$('#oldriver').onclick=()=>{e('drone_oldriver');st.gis.drone=true;save();toast('旧河槽位置已发送到GIS临时图层')}}

function article(id){if(id==='oldmissing')return['地方新闻档案 / 2012补录','2011雨季，三名徒步者在乌伦河上游失踪','公开记录彼此并不完全一致。',`<p>2011年11月，三名私人徒步者进入乌伦河上游后失联。县级搜救简报把最后可信位置写成“第三支流以北”，而家属保存的卫星短信则写着“改变路线，跟当地向导走半天”。两者并不矛盾，但长期被二次报道合并成同一地点。</p><p>失踪者冯祁负责摄影。家属补交的装备清单列有一台银色 <b>Sony DSC-W220</b>，机身序列号末四位 <b>7134</b>。搜救期间没有找到相机和存储卡。</p><p>2026共享目录中出现一台同型号旧相机；型号相似本身不能证明它与2011年设备相同。</p><p>2013年一篇地方论坛帖声称三人加入非法采木队，但没有提供一手来源；警方也从未采纳这一说法。</p>`];if(id==='fieldnote')return['人类学资料数字化计划 / 未出版田野材料','1978乌伦河上游工作笔记：名字、身体与“留下”','记录者自己也多次承认翻译可能错误。',`<p>笔记者把近似 <i>amokha</i> 的词先译成“村庄”，三周后又改成“属于里面的人”。同一个词既可能指地方，也可能指关系。</p><p>笔记里反复出现 ${glyph('body')}、${glyph('name')}、${glyph('river')}、${glyph('rain')} 和 ${glyph('dream')}。记录者认为前两者与身体和称名有关，但在页边写了“不要建立一一对应词典”。</p><h2>饮食与纪念</h2><p>最具争议的仪式发生在亲属死亡后。部分家庭会分食极少量组织，另一些家庭只保留骨、名字或衣物。火通常被认为会让“可以留下的东西”失去去处，骨常归河。儿童第一次参加可以拒绝。</p><p>同一批笔记也记录了反对者、折衷者和不参加仪式的家庭。记录者特别提到一位绘画者Eru，但附页没有进入正式档案。</p>`];if(id==='painter')return['1978—1980 未归档附页','Eru的五张Sena肖像','同一个人被反复画下；文字比脸先消失。',`<p>Eru的伴侣Sena死在一次雨季外出中，遗体没有带回。长老提出以名字、衣物和亲属替代传统留身，他拒绝了其中一部分，却并没有否认留身礼本身。</p><div class="portraits">${[1,2,3,4,5].map((n,i)=>`<figure><img src="assets/photos/sena_${n}.webp"><figcaption>${['今天还记得她把头发扎在右边。','她笑的时候左边嘴角先动。','昨天想不起她手背上的痣在哪边。','今天画眼睛用了三次。','今天已经画不像她了。'][i]}</figcaption></figure>`).join('')}</div><blockquote>“如果一个人只能在肉里留下，为什么还要教孩子写名字？”</blockquote><p>这句话没有使Eru被逐出。后来的记录显示他仍参与亲属仪式，也负责儿童识字墙。分歧发生在“什么能够保存一个人”，而不是“要不要成为阿摩迦人”。</p>`];if(id==='lastlog')return['周野 / 卫星箱本地缓存','最后完整日志','创建时间 09/23 02:41，上传未完成。',`<p>我已经不知道今天到底算第几天。外面一直有人走，但不是所有人都在守着我们。</p><p>高桥昨天终于把那几个词拆开。他说我们把他们理解成“吃人”太简单。肉只是很多种留下人的方法之一，而且是最老、最有权力的一种。</p><p>林澈昨天还活着。我确定，因为有人送水时我听见她在隔壁说话。今天早上又听见她的声音。进来的女人不会普通话，可她重复了林澈昨晚说过的一句话，连停顿都一样。我不知道这是学的，还是高桥说的那种“声音留下”。</p><p>画画的人昨晚把一块电池和折起来的纸塞到旧河槽。他不会我们的语言，只指自己画的那个女人，再指脑袋。高桥说他大概是在说：记住不一定要把东西放进身体。</p><p>他把路标的缺口刻反了。许放一开始说那是错的，后来我们看地形才发现，按“错”的方向走会回到旧河道。按“对”的方向才会进中央空地。</p><p>如果你看到这个，不要来找我。把地图、无人机位置和旧河道交给搜救。别把这里说成一群疯子。那样他们会误判。这里有人想留住我们，也有人在帮我们走。</p><blockquote>我最怕的不是他们相信这些。我最怕的是，我开始理解他们为什么会相信。</blockquote>`];return['档案','资料不存在','',`<p>该资料暂不可用。</p>`]}
function renderArticle(){const id=param('id')||'oldmissing',a=article(id);if(id==='oldmissing'&&has('camera_seen'))e('camera_match');if(id==='fieldnote')e('fieldnote_read');if(id==='painter')e('painter_read');if(id==='lastlog')e('last_log');app.innerHTML=`<section class="archive"><header class="archive-head">AZERA DIGITAL ARCHIVE / DOCUMENT VIEWER</header><article class="archive-paper"><div class="eyebrow">${a[0]}</div><h1>${a[1]}</h1><div class="deck">${a[2]}</div><div class="body">${a[3]}${id==='fieldnote'?'<p><button id="searchEru">检索附页索引</button></p>':''}</div></article></section>`;if($('#searchEru'))$('#searchEru').onclick=()=>location.hash='#search?q='+encodeURIComponent('Eru Sena 肖像')}

const FMAP=['####################','#......~~~~~........#','#..##..~~~~..####...#','#......~~~~......#..#','#.####.....#####.#..#','#......##........#..#','#.####....#####.....#','#....#..............#','#....#.######.######','#.................G#','####################'];
function renderFlash(){visit('flash');app.innerHTML=`<div class="oldwrap"><section class="oldsite"><div class="oldbanner"><h1>林线之外</h1><p>Beyond the Tree Line · 个人野外笔记 / 2011</p></div><div class="oldnav">首页　游戏　地图　碎片　留言簿　友情链接</div><div class="oldgrid"><aside class="oldside">最近更新<br>2011.08.07<br><br>“地图不是路。路是人走过以后留下的错误。”<br><br><span class="counter">0043172</span></aside><main class="oldmain"><h2>林线之外 v0.7</h2><div class="gameframe"><canvas id="game" width="640" height="430"></canvas></div><p>方向键移动。旧浏览器里声音可能失效。</p></main><aside class="oldside oldright"><b>作者</b><br>K. Nomura<br><br><b>留言簿</b><br>2011/07/13<br>“第三张地图右边是不是死路？”<br><br>2011/08/02<br>“你把现实坐标画进去了？”<br><br><button class="oldbutton" id="resetgame">重新开始</button></aside></div></section></div>`;initFlash();$('#resetgame').onclick=()=>{st.flash={x:2,y:8,gate:false};save();initFlash()}}
function initFlash(){const cv=$('#game');if(!cv)return;const ctx=cv.getContext('2d'),cw=32,ch=39;function draw(){ctx.fillStyle='#030805';ctx.fillRect(0,0,640,430);for(let y=0;y<FMAP.length;y++)for(let x=0;x<FMAP[y].length;x++){const c=FMAP[y][x];if(c==='#'){ctx.fillStyle='#143126';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}else if(c==='~'){ctx.fillStyle='#0d3640';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}else if(c==='G'){ctx.fillStyle='#6d1e18';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}}ctx.fillStyle='#dedcc4';ctx.fillRect(st.flash.x*cw+10,st.flash.y*ch+10,12,20);ctx.fillStyle='#82b69c';ctx.font='12px monospace';ctx.fillText('方向键 / ARROWS',12,18)}draw();cv.tabIndex=0;cv.focus();cv.onkeydown=ev=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[ev.key];if(!d)return;ev.preventDefault();const nx=st.flash.x+d[0],ny=st.flash.y+d[1],c=FMAP[ny]?.[nx];if(c&&c!=='#'&&c!=='~'){st.flash.x=nx;st.flash.y=ny;if(c==='G'&&!st.flash.gate){save();openGatePuzzle();return}save();draw()}}}

function openGatePuzzle(){const choices=['rain','road','return','home','eye','body','river','name'];let seq=[];modal.innerHTML=`<div class="modalbox" style="width:min(760px,92vw);height:auto;background:#ded4b7;color:#332c20;padding:34px;border:5px ridge #8b826a"><button class="modalclose">×</button><h2 style="font:24px Georgia,serif;margin-top:0">石门刻痕</h2><p style="font:11px Tahoma;line-height:1.7">四个凹槽被反复摩擦过。旁边没有翻译，只有作者在网页边栏留下的一句："after the rain, take the old road back inward."</p><div id="gateSlots" style="display:flex;gap:8px;min-height:62px;border:2px inset #aaa;background:#eee5cc;padding:8px;margin:18px 0"></div><div id="gateChoices" style="display:flex;flex-wrap:wrap;gap:8px">${choices.map(k=>`<button data-gate="${k}" class="oldbutton">${glyph(k)}</button>`).join('')}</div><p id="gateMsg" style="font:10px Tahoma;height:18px"></p><button id="gateClear" class="oldbutton">清空</button> <button id="gateTry" class="oldbutton">按下石板</button></div>`;const draw=()=>{$('#gateSlots').innerHTML=seq.map(k=>glyph(k)).join('')};$$('[data-gate]').forEach(b=>b.onclick=()=>{if(seq.length<4){seq.push(b.dataset.gate);draw()}});$('#gateClear').onclick=()=>{seq=[];draw();$('#gateMsg').textContent=''};$('#gateTry').onclick=()=>{if(seq.join(',')==='rain,road,return,home'){st.flash.gate=true;e('flash_gate');modal.innerHTML='';toast('石门后的隐藏地图被记录下来')}else $('#gateMsg').textContent='石板没有反应。'};$('.modalclose').onclick=()=>modal.innerHTML=''}

function renderNotes(){visit('notes');app.innerHTML=`<section class="notespage"><div class="notebook"><div class="paper"><h1>野外笔记</h1><textarea id="notesArea" placeholder="自由记录名字、坐标、怀疑、互相矛盾的来源……">${esc(st.notes)}</textarea></div><div class="paper"><h1>字符草记</h1><p style="font:11px/1.8 var(--serif)">这些释义不会被系统判定对错，只是你自己的记号。</p><div class="glyphnotes">${GKEY.map(k=>`<div class="gentry">${glyph(k)}<input data-g="${k}" value="${esc(st.glyphNotes[k]||'')}" placeholder="你的理解"></div>`).join('')}</div></div></div></section>`;$('#notesArea').oninput=ev=>{st.notes=ev.target.value;save()};$$('[data-g]').forEach(i=>i.oninput=ev=>{st.glyphNotes[i.dataset.g]=ev.target.value;save()})}

function renderRescue(){visit('rescue');const ready=has('final_ready');app.innerHTML=`<section class="sar"><header class="sarhead"><strong>国家应急管理部 · 失联人员搜救补充系统</strong><small>案件 EM-2026-0924-ARZ</small></header><nav class="sarnav">任务管理　信息上报　协同单位　卫星数据　历史案件</nav><main class="sarbox"><h1>阿泽拉雨林科考队失联事件 / 补充材料</h1><p style="font-size:10px;color:#68757c">只提交可供现场复核的事实、坐标与来源。未经证实的仪式解释不应作为导航依据。</p><form id="sarform"><fieldset><legend>1. 最后可信区域</legend><label>区域中心<input name="coord" placeholder="例如 2.4175N, 114.226E"></label><label>主要依据<select name="basis"><option value="">请选择</option><option>GPS轨迹 + 降雨时窗</option><option>GPS轨迹 + 现场改线记录</option><option>无人机旧河槽 + 现场改线记录</option></select></label></fieldset><fieldset><legend>2. 风险说明</legend><label>现场情况<textarea name="risk" placeholder="仅写可复核事实"></textarea></label></fieldset><div id="sarerr" class="error"></div><button>提交补充材料</button></form></main></section>`;$('#sarform').onsubmit=ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),coord=(fd.get('coord')||'').trim(),basis=fd.get('basis'),risk=(fd.get('risk')||'').trim();if(!ready){$('#sarerr').textContent='当前资料仍不足以建立可复核搜救区域。';return}if(!coord||!basis||risk.length<20){$('#sarerr').textContent='请填写坐标、证据来源，并至少提供20字风险说明。';return}st.submitted=true;save();go('ending')}}
function renderEnding(){app.innerHTML=`<section class="ending"><article class="bulletin"><div style="border-bottom:3px double #333;padding-bottom:12px;font-size:10px">国家应急管理部 / 搜救通报</div><h1>阿泽拉雨林科考队搜救行动阶段性通报</h1><p>搜救队在乌伦河旧河槽附近发现部分科考装备、临时避雨点与一部损坏的卫星终端。现场未发现完整营地。受持续降雨和地形影响，大范围地面搜索已转为重点区域复查。</p><p>有关当地居民点、仪式活动及失踪人员后续去向的信息仍在核实。公开通报不采纳无法由现场证据独立验证的网络材料。</p><p>搜救协调组将继续与家属、项目单位及地方社区保持联系。</p></article><div class="notif"><b>Cloudline</b><br>共享相册索引已更新：${photos.length+1} 项<br><span style="color:#777">所有者：周野 · 活动时间 2分钟前</span></div></section>`}

function render(){derive();sitePanel.hidden=true;modal.innerHTML='';updateChrome();const r=route();({chat:renderChat,portal:renderPortal,wild:renderWild,map:renderMap,cloud:renderCloud,search:renderSearch,medical:renderMedical,drone:renderDrone,article:renderArticle,flash:renderFlash,notes:renderNotes,rescue:renderRescue,ending:renderEnding}[r]||renderChat)();audioScene()}
render();
})();
