'use strict';

function renderSite(p){
  const h=p.host;
  if(h==='newtab.local')return renderNewTab();
  if(h==='fieldtalk.local')return renderFieldTalk(p);
  if(h==='azera-rainforest.org')return renderPortal(p);
  if(h==='wildtrace.app')return renderWild(p);
  if(h==='atlas.azera-research.org')return renderMap(p);
  if(h==='cloudline.app')return renderCloud(p);
  if(h==='echosearch.net')return renderSearch(p);
  if(h==='fieldnotes.local')return renderNotes(p);
  if(h==='docs.azera-research.org')return renderMedical(p);
  if(h==='survey.azera-research.org')return renderDrone(p);
  if(h==='linebeyond.net')return renderOldSite(p);
  if(h==='sar.azera.gov')return renderRescue(p);
  if(h==='satcache.azera-research.org')return renderSatCache(p);
  const doc=WEB_DOCS.find(d=>p.raw===d.url || p.raw.startsWith(d.url+'?'));
  if(doc)return renderWebDoc(doc,p);
  render404(p);
}

function renderNewTab(){
  const recent=[...st.history].reverse().filter((x,i,a)=>a.indexOf(x)===i).slice(0,8);
  app.innerHTML=`<section class="newtab"><div class="newtab-inner"><div class="newtab-search"><span>EchoSearch</span><input id="ntq" placeholder="搜索互联网或输入网址" autofocus></div><div class="quicklinks">${st.bookmarks.slice(0,8).map(u=>`<button data-nav="${esc(u)}"><b>${esc(titleFor(u))}</b><small>${esc(parseUrl(u).host)}</small></button>`).join('')}</div><h2>最近访问</h2><div class="recent-list">${recent.map(u=>`<button data-nav="${esc(u)}"><span>${esc(titleFor(u))}</span><small>${esc(u)}</small></button>`).join('')}</div></div></section>`;
  $('#ntq').onkeydown=ev=>{if(ev.key==='Enter')nav(knownUrl(ev.target.value))};
}

function avatar(name){
  const entry=Object.values(PEOPLE).find(x=>x.name===name); if(entry)return `<span class="avatar" style="--av:${entry.color}">${entry.initial}</span>`;
  const ch=name?.[0]||'·'; return `<span class="avatar system-avatar">${ch}</span>`;
}
const LINK_URL={
  'portal-home':'azera-rainforest.org/season-2026','map':'atlas.azera-research.org/project/UL09','medical':'docs.azera-research.org/medical-log','cloud':'cloudline.app/shared/zhouye-field','drone':'survey.azera-research.org/review/0922','cache':'satcache.azera-research.org/ARZ-04/object/0382','rescue':'sar.azera.gov/case/EM-2026-0924-ARZ/supplement'
};
function messageMarkup(m,i,channel){
  const [time,name,text,link]=m; const sys=name==='系统'||name==='卫星服务台';
  let reactions=''; if(channel==='field'&&['09/20 15:28','09/20 15:31','09/21 18:56'].includes(time))reactions='<div class="reactions"><span>👍 3</span><span>😅 2</span></div>';
  const attachment=link&&LINK_URL[link]?`<button class="ft-attachment" data-nav="${LINK_URL[link]}"><span class="fileicon">↗</span><span>${link==='map'?'UL-09 GIS会话':link==='medical'?'现场医疗记录':link==='cloud'?'Cloudline共享目录':link==='drone'?'0922无人机代理帧':link==='cache'?'ARZ-04缓存恢复对象':link==='rescue'?'搜救补充材料':'2026野外季项目页'}</span><small>打开</small></button>`:'';
  return sys?`<div class="ft-system"><time>${time}</time><span>${esc(text)}</span></div>`:`<article class="ft-message" data-msg="${channel}-${i}">${avatar(name)}<div class="message-body"><div class="message-head"><b>${esc(name)}</b><time>${time}</time>${name==='罗岚'&&channel==='coord'?'<span class="status-dot offline"></span>':''}</div><p>${esc(text)}</p>${attachment}${reactions}</div></article>`;
}
function renderFieldTalk(p){
  const q=p.query; const channel=q.get('channel')||st.chatChannel||'coord'; st.chatChannel=CHANNELS[channel]?channel:'coord'; save();
  if(p.path.includes('/search'))return renderFieldTalkSearch(p);
  if(p.path.includes('/files'))return renderFieldTalkFiles(p);
  const c=CHANNELS[st.chatChannel]; let msgs=[...c.messages];
  if(st.chatChannel==='coord'&&has('cache_recovered'))msgs.push(['09/24 16:52','卫星服务台','ARZ-04缓存重放结束。恢复到一段未完整上传的本地文本，创建者字段为周野。项目法务已确认可以向现有访客开放只读副本。','cache']);
  if(st.chatChannel==='coord'&&has('cache_recovered'))msgs.push(['09/24 16:57','罗岚','卫星服务台刚把那段文本挂出来。我还没看完，只确认过创建时间和设备号。你如果要看，原文在缓存页，不是我转述。','cache']);
  if(st.chatChannel==='coord'&&has('rescue_ready'))msgs.push(['09/24 17:18','马建 · 搜救联络','案件补充入口已经对项目访客开放。只收可复核坐标和来源组合；居民身份和仪式解释先不要写进路线依据。','rescue']);
  const info=q.get('info')==='1';
  const channels=[['coord','后方协调'],['field','# 现场实时'],['gear','# 后勤与装备'],['bio','# 生物记录'],['drone','# 影像与无人机'],['archive','# 项目旧讨论']];
  app.innerHTML=`<section class="ft-app ${info?'with-info':''}">
    <aside class="ft-workspaces"><div class="ftmark">FT</div><div class="ws active">AZ</div><button class="ws" data-nav="newtab.local">＋</button></aside>
    <aside class="ft-nav"><div class="workspace-name">阿泽拉项目 <span>⌄</span></div><button class="ft-searchbtn" data-nav="fieldtalk.local/workspace/azera/search">⌕　搜索消息、文件、成员</button><div class="nav-label">消息</div>${channels.map(x=>`<button class="ft-channel ${st.chatChannel===x[0]?'active':''}" data-ftchannel="${x[0]}">${x[1]}${x[0]==='field'?'<span class="unread">6</span>':''}</button>`).join('')}<div class="nav-label">私信</div><button class="ft-channel ${st.chatChannel==='zhou'?'active':''}" data-ftchannel="zhou">周野</button><div class="nav-label">资料</div><button class="ft-channel" data-nav="fieldtalk.local/workspace/azera/files">共享文件</button><div class="nav-label">成员</div>${Object.values(PEOPLE).filter(x=>!['luo'].includes(Object.keys(PEOPLE).find(k=>PEOPLE[k]===x))).slice(0,6).map((x,i)=>`<button class="ft-person" data-member="${x.name}">${avatar(x.name)}<span>${x.name}</span><i class="presence ${i===0?'away':i<4?'offline':'away'}"></i></button>`).join('')}</aside>
    <main class="ft-conversation"><header class="ft-roomhead"><div><h1>${esc(c.title)}</h1><span>${c.members.length} 成员 · 归档同步</span></div><div class="room-actions"><button id="roomSearch" title="在频道中搜索">⌕</button><button data-nav="fieldtalk.local/workspace/azera?channel=${st.chatChannel}&info=${info?'0':'1'}" title="会话信息">ⓘ</button></div></header><div class="ft-day"><span>2026年9月</span></div><div class="ft-stream">${msgs.map((m,i)=>messageMarkup(m,i,st.chatChannel)).join('')}${pollution()>=3&&st.chatChannel==='coord'?'<div class="typing-event"><span></span>周野正在输入…</div>':''}</div><footer class="ft-compose"><div>该工作区处于事故保全模式，访客账户仅可读取历史内容。</div></footer></main>
    ${info?`<aside class="ft-info"><header><b>会话信息</b><button data-nav="fieldtalk.local/workspace/azera?channel=${st.chatChannel}">×</button></header><section><h3>成员</h3>${c.members.map(n=>`<div class="info-member">${avatar(n)}<span>${n}</span></div>`).join('')}</section><section><h3>同步</h3><p>卫星文字优先。代理图可能比拍摄时间晚数小时到达。</p></section><section><h3>权限</h3><p>事故保全状态；访客只读。</p></section></aside>`:''}
  </section>`;
  $$('[data-ftchannel]').forEach(b=>b.onclick=()=>nav(`fieldtalk.local/workspace/azera?channel=${b.dataset.ftchannel}`));
  $('#roomSearch').onclick=()=>nav(`fieldtalk.local/workspace/azera/search?channel=${st.chatChannel}`);
  $$('[data-member]').forEach(b=>b.onclick=()=>showMemberPopover(b.dataset.member));
  observeChatEvidence(st.chatChannel,msgs);
}
function observeChatEvidence(channel,msgs){
  // Merely opening a channel is not enough; flags come from explicit content-linked actions or searching.
  if(channel==='field'){
    // mark only when user has scrolled far enough to expose the relevant records
    const stream=$('.ft-stream'); if(stream)stream.addEventListener('scroll',()=>{if(stream.scrollTop+stream.clientHeight>stream.scrollHeight*.72){flag('field_route_read');flag('field_contact_read')}});
  }
}
function showMemberPopover(name){const p=Object.values(PEOPLE).find(x=>x.name===name);if(!p)return;modal.innerHTML=`<div class="member-pop"><button class="close">×</button>${avatar(name)}<h2>${p.name}</h2><p class="member-role">${p.role}</p><p>${p.bio}</p><p>${p.history}</p></div>`;$('.member-pop .close').onclick=()=>modal.innerHTML=''}
function renderFieldTalkSearch(p){
  const q=p.query.get('q')||''; const channel=p.query.get('channel')||''; let hits=[];
  if(q){for(const [ck,c] of Object.entries(CHANNELS)){if(channel&&ck!==channel)continue;c.messages.forEach((m,i)=>{if((m[1]+' '+m[2]).toLowerCase().includes(q.toLowerCase()))hits.push({ck,c,i,m})})} if(/改线|第三支流|西南|旧河床/.test(q))flag('field_route_read'); if(/交换|四个人|屋顶|相机/.test(q))flag('field_contact_read')}
  app.innerHTML=`<section class="ft-searchpage"><header><button data-nav="fieldtalk.local/workspace/azera?channel=${channel||'coord'}">←</button><input id="ftq" value="${esc(q)}" placeholder="搜索消息、人员或文件" autofocus><span>${q?hits.length+' 条结果':''}</span></header><main>${q?hits.map(h=>`<article><div>${avatar(h.m[1])}<b>${esc(h.m[1])}</b><time>${h.m[0]} · ${h.c.title}</time></div><p>${highlight(h.m[2],q)}</p><button data-nav="fieldtalk.local/workspace/azera?channel=${h.ck}">在频道中打开</button></article>`).join(''):'<div class="ft-searchhint">可以搜索姓名、设备、路线、日期或消息正文。</div>'}</main></section>`;
  $('#ftq').onkeydown=ev=>{if(ev.key==='Enter')nav(`fieldtalk.local/workspace/azera/search?${channel?'channel='+channel+'&':''}q=${encodeURIComponent(ev.target.value.trim())}`)};
}
function highlight(text,q){if(!q)return esc(text);return esc(text).replace(new RegExp(escRegex(q),'ig'),m=>`<mark>${m}</mark>`)}
function escRegex(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function renderFieldTalkFiles(p){
  const files=[['UL09_route_plan_v3.geojson','31 KB','许放 · 09/18','atlas.azera-research.org/project/UL09'],['community_contact_protocol.pdf','412 KB','姚敏 · 08/31','azera-rainforest.org/data'],['DJI_0508_PROXY.zip','8.4 MB','陈栩 · 09/23','survey.azera-research.org/review/0922'],['medical-log.xlsx','94 KB','林澈 · 09/23','docs.azera-research.org/medical-log'],['field-photo-share','共享目录','周野 · 09/19','cloudline.app/shared/zhouye-field']];
  app.innerHTML=`<section class="ft-filepage"><header><button data-nav="fieldtalk.local/workspace/azera?channel=coord">← 返回工作区</button><h1>共享文件</h1><input id="fileq" placeholder="筛选文件"></header><table><thead><tr><th>名称</th><th>大小</th><th>上传者 / 时间</th><th></th></tr></thead><tbody>${files.map(f=>`<tr data-file-row="${f[0].toLowerCase()}"><td>${f[0]}</td><td>${f[1]}</td><td>${f[2]}</td><td><button data-nav="${f[3]}">打开</button></td></tr>`).join('')}</tbody></table></section>`; $('#fileq').oninput=ev=>{$$('[data-file-row]').forEach(r=>r.hidden=!r.dataset.fileRow.includes(ev.target.value.toLowerCase()))};
}

const PORTAL_NAV=[['/season-2026','项目首页'],['/research','研究方向'],['/field-log','野外季日志'],['/data','公开数据'],['/people','团队'],['/news','新闻与公告']];
function portalHeader(active){return `<header class="acrp-head"><a data-nav="azera-rainforest.org/season-2026" class="acrp-logo">ACRP</a><nav>${PORTAL_NAV.map(n=>`<a data-nav="azera-rainforest.org${n[0]}" class="${active===n[0]?'active':''}">${n[1]}</a>`).join('')}</nav><button data-nav="echosearch.net/search?q=${encodeURIComponent('site:azera-rainforest.org 乌伦')}">⌕</button></header>`}
function renderPortal(p){
  const path=p.path.replace(/\/$/,'')||'/season-2026';
  if(path.startsWith('/people/'))return renderPersonPage(path.split('/').pop());
  if(path.startsWith('/data/file'))return renderDataset(p.query.get('name')||'');
  if(path==='/research')return renderResearch();
  if(path==='/field-log')return renderFieldLog();
  if(path==='/data')return renderDataPage();
  if(path==='/people')return renderPeople();
  if(path==='/news')return renderPortalNews();
  renderPortalHome();
}
function renderPortalHome(){
  app.innerHTML=`<section class="acrp">${portalHeader('/season-2026')}<div class="acrp-hero"><img src="assets/photos/aerial_river.webp" alt="乌伦河上游航拍"><div class="hero-shade"></div><div class="hero-meta">FIELD SEASON 2026<br>ULEN UPPER BASIN</div><div class="hero-text"><h1>乌伦河上游<br>跨学科联合野外季</h1><p>夜行灵长类声学、水文测绘、植物群落样方与季节性人类活动调查。</p><a data-nav="azera-rainforest.org/research">查看研究方法 →</a></div><div class="hero-season">2026 / 09.18—10.02</div></div>
  <section class="acrp-intro"><aside>关于本季</aside><div><p class="lead">本项目由雨林大学、人类学研究中心与阿泽拉自然史博物馆共同实施。2026野外季计划在乌伦河上游完成三个声学样区、两条水文断面、四组植物样方和一轮社区接触记录。</p><p>项目区域并非“无人区”。研究许可要求团队在遇到季节采集者或居民时优先停止拍摄、确认接触意愿，并把人员影像与开放数据分离保存。</p></div></section>
  <section class="acrp-stripe"><div><span>06</span>现场成员</div><div><span>04</span>研究主题</div><div><span>08</span>公开数据集</div><div><span>03</span>合作机构</div></section>
  <section class="acrp-editorial"><article><time>09/22</time><h2>野外季日志：路线调整与水位</h2><p>连续降雨影响北段过河点，队伍按现场风险流程调整路线。</p><a data-nav="azera-rainforest.org/field-log">进入日志</a></article><article><time>08/31</time><h2>社区接触伦理流程公开</h2><p>2026版流程新增代理影像与卫星同步说明。</p><a data-nav="azera-rainforest.org/data">查看数据与文件</a></article><article><time>07/18</time><h2>声学设备校准完成</h2><p>UL-A1—A6记录仪完成出发前校准。</p><a data-nav="azera-rainforest.org/research">研究方法</a></article></section>
  <footer class="acrp-foot">Azera Rainforest Cooperative Research Program · Research permit ARZ-UL-2026-44 · <a data-nav="azera-rainforest.org/news">Newsroom</a></footer></section>`;
}
function renderResearch(){app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/research')}<header class="page-hero"><div class="eyebrow">RESEARCH / 2026 FIELD SEASON</div><h1>研究不是寻找“未知”，<br>而是把不同证据放回同一处现场。</h1><p>2026野外季以四条互相独立的资料链工作：声学记录、水文与地形、植被样方、社区接触。任何单一来源都不作为异常现象的最终解释。</p></header><div class="method-list">
  <section><b>01</b><h2>声学生态</h2><p>六台自动记录仪在黄昏与凌晨窗口采样。候选叫声先按频段和重复结构分类，再与天气、蝉鸣和人类活动时段交叉核对。</p><dl><dt>设备</dt><dd>UL-A1—A6</dd><dt>采样</dt><dd>48kHz / 24bit</dd></dl></section>
  <section><b>02</b><h2>水文与路线</h2><p>两个便携雨量筒、GPS原始轨迹和公开水文站构成最低限度的路线复核。峡谷环境允许出现单点漂移，因此不会手工删除“难看”的轨迹点。</p><dl><dt>设备</dt><dd>GPSMAP 67i ×2</dd><dt>等高</dt><dd>40m</dd></dl></section>
  <section><b>03</b><h2>植物群落</h2><p>四组样方用于记录树种、胸径和林下覆盖。样方数据独立归档，与路线和社区接触资料分开质控。</p><dl><dt>样方</dt><dd>20×20m</dd><dt>编号</dt><dd>Q-A—Q-D</dd></dl></section>
  <section><b>04</b><h2>社区接触</h2><p>团队不把季节采集者自动归类为“居民”。影像、称名和地点必须分开记录，翻译不确定时保留原音。</p><dl><dt>伦理版本</dt><dd>v2026.3</dd><dt>公开影像</dt><dd>默认去标识</dd></dl></section>
  </div><footer class="acrp-foot"><a data-nav="azera-rainforest.org/data">公开数据与方法附件 →</a></footer></section>`}
function renderFieldLog(){app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/field-log')}<header class="log-head"><div><div class="eyebrow">FIELD NOTES</div><h1>2026野外季日志</h1></div><p>这里只保留项目原计划公开的每日摘要。个人医疗、居民影像与内部风险讨论不在公开日志中。</p></header><main class="fieldlog">${FIELD_LOGS.map((l,i)=>`<article><time>2026.${l.date}</time><div><h2>${l.title}</h2><p>${l.text}</p>${i===1?'<p class="minor">天气：间歇暴雨 / 河口水位 +0.31m / 记录仪UL-A3完成更换。</p>':''}${i===2?'<p class="minor">公开影像只保留环境和营地，不发布接触者正脸。</p>':''}</div></article>`).join('')}<article class="log-stopped"><time>2026.09.23</time><div><h2>—</h2><p>本日摘要未提交。</p></div></article></main></section>`}
function renderDataPage(){app.innerHTML=`<section class="acrp acrp-page data-page">${portalHeader('/data')}<header class="data-head"><div class="eyebrow">OPEN DATA</div><h1>公开数据与文件</h1><p>开放数据按CC BY-NC 4.0发布。现场人员影像、精确居民位置和医疗记录不进入此页。</p></header><div class="dataset-table"><div class="dataset-row head"><span>文件</span><span>更新时间</span><span>格式</span><span>说明</span></div>${DATASETS.map(d=>`<button class="dataset-row" data-nav="azera-rainforest.org/data/file?name=${encodeURIComponent(d[0])}"><span><b>${d[0]}</b><small>${d[1]}</small></span><span>${d[2]}</span><span>${d[3]}</span><span>${d[4]}</span></button>`).join('')}</div><aside class="data-note"><b>版本说明</b><p>计划路线只用于审批与后勤，不代表现场最终行走路径。2017调查仅覆盖河东岸样线。</p></aside></section>`}
function renderDataset(name){const d=DATASETS.find(x=>x[0]===name)||DATASETS[0];let rows='';if(name.includes('rain'))rows=`<pre>timestamp,rain_mm,river_stage_m\n09/21 18:00,4.2,+0.12\n09/21 21:00,13.8,+0.25\n09/22 00:00,21.1,+0.38\n09/22 06:00,18.7,+0.53\n09/22 12:00,24.2,+0.69\n09/22 14:00,4.0,+0.74</pre>`;else if(name.includes('route'))rows=`<pre>{\n  "name": "UL09 planned route v3",\n  "crs": "EPSG:4326",\n  "warning": "approval route; not a live track"\n}</pre>`;else rows=`<pre># Preview only\nfile: ${esc(d[0])}\nupdated: ${d[2]}\nformat: ${d[3]}\n\nThis public preview contains no personal or restricted coordinates.</pre>`;app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/data')}<main class="file-preview"><a data-nav="azera-rainforest.org/data">← 返回公开数据</a><div class="eyebrow">PUBLIC DATASET</div><h1>${esc(d[0])}</h1><p>${d[4]}</p>${rows}<a class="dataset-download" href="assets/data/${esc(d[0])}" download>下载原文件</a></main></section>`;}
function personKey(slug){return {zhou:'zhou','zhou-ye':'zhou','lin-che':'lin','chen-xu':'chen','ken-takahashi':'gao','xu-fang':'xu','wang-jingshan':'wang'}[slug]||slug}
function renderPeople(){const order=['zhou','lin','chen','gao','xu','wang'];app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/people')}<header class="people-head"><div class="eyebrow">FIELD TEAM</div><h1>2026现场团队</h1><p>六名现场成员来自不同机构。这里只列项目职责与公开履历。</p></header><main class="people-list">${order.map((k,i)=>{const x=PEOPLE[k];return `<article><span class="person-index">0${i+1}</span><div><h2>${x.name}<small>${x.en}</small></h2><p>${x.role}</p></div><p>${x.bio}</p><button data-nav="azera-rainforest.org/people/${['zhou-ye','lin-che','chen-xu','ken-takahashi','xu-fang','wang-jingshan'][i]}">查看履历 →</button></article>`}).join('')}</main></section>`}
function renderPersonPage(slug){const k=personKey(slug),x=PEOPLE[k]||PEOPLE.zhou;const publications={zhou:['2019—2025 民间路线复核志愿记录','2024 乌伦上游公开步道GPS校正'],lin:['2023 野外低体温早期识别培训','2025 阿泽拉南部营地医疗回顾'],chen:['2024 低带宽环境中的无人机代理图工作流','2025 河谷正射影像拼接误差说明'],gao:['2022 区域称名与内外群体词研究','2024 船夫口述地名的三层转写'],xu:['2023 雨季路线风险手册（内部）','2025 山洪后撤营决策复盘'],wang:['1998—2025 夜行灵长类声学系列论文','2021 阿泽拉北部声景长期变化']}[k]||[];app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/people')}<main class="person-page"><a data-nav="azera-rainforest.org/people">← 团队</a><div class="person-title"><span>${x.initial}</span><div><div class="eyebrow">FIELD TEAM / 2026</div><h1>${x.name}</h1><p>${x.en} · ${x.role}</p></div></div><section><h2>公开履历</h2><p>${x.bio}</p></section><section><h2>过往工作</h2><p>${x.history}</p></section><section><h2>相关资料</h2><ul>${publications.map(p=>`<li>${p}</li>`).join('')}</ul></section></main></section>`}
function renderPortalNews(){const news=[['09/24','关于2026野外季团队失联的情况说明','学校已与当地应急部门、保险及家属建立联络。为避免干扰搜救，不公开未经验证的位置和居民影像。'],['09/12','2026野外季设备清单与开放数据计划','本季公开数据包括声学索引、水文、样方和经处理的路线数据。'],['08/31','社区接触伦理流程更新至v2026.3','新增代理影像、称名不确定性和低带宽同步说明。'],['07/18','六台声学记录仪完成校准','UL-A1—A6完成实验室噪声底复核。']];app.innerHTML=`<section class="acrp acrp-page">${portalHeader('/news')}<header class="news-head"><div class="eyebrow">NEWSROOM</div><h1>新闻与公告</h1></header><main class="news-list">${news.map((n,i)=>`<article><time>2026.${n[0]}</time><div><h2>${n[1]}</h2><p>${n[2]}</p>${i===0?'<a data-nav="echosearch.net/search?q='+encodeURIComponent('阿泽拉 科考队 失联')+'">查看公开检索结果</a>':''}</div></article>`).join('')}</main></section>`}

function wildGlobalNav(active=''){return `<header class="wt-global"><b data-nav="wildtrace.app/explore">WildTrace</b><nav><a data-nav="wildtrace.app/explore" class="${active==='explore'?'active':''}">探索</a><a data-nav="wildtrace.app/routes" class="${active==='routes'?'active':''}">路线</a><a data-nav="wildtrace.app/community" class="${active==='community'?'active':''}">社区</a><a data-nav="wildtrace.app/gear" class="${active==='gear'?'active':''}">装备</a></nav><div class="wt-search"><input id="wtSearch" placeholder="搜索路线、地点或用户"><span>⌕</span></div></header>`}
function renderWild(p){
  if(p.path==='/explore')return renderWildExplore(); if(p.path==='/routes')return renderWildRoutes(); if(p.path==='/community')return renderWildCommunity(); if(p.path==='/gear')return renderWildGear();
  const tab=p.query.get('tab')||'activity'; st.wildTab=tab;save();
  const tabs=[['activity','动态'],['routes','路线'],['photos','相册'],['gear','装备'],['about','关于']];
  let content='';
  if(tab==='activity')content=`<div class="wt-feed">${POSTS.map((p,i)=>`<article class="wt-post"><time>${p[0]}</time><div class="wt-postbody"><h2>${p[1]}</h2><p>${p[2]}</p>${p[3]?`<img src="assets/photos/${p[3]}" alt="${esc(p[1])}">`:''}<footer><span>♡ ${38+(i*17)%91}</span><span>评论 ${i%5+1}</span><span>公开</span></footer></div></article>`).join('')}</div>`;
  else if(tab==='routes')content=`<div class="wt-routes"><div class="wt-route-head"><span>日期</span><span>路线</span><span>距离</span><span>爬升</span><span>状态</span></div>${ROUTES.map(r=>`<div><span>${r[0]}</span><b>${r[1]}</b><span>${r[2]}</span><span>${r[3]}</span><span>${r[4]}</span></div>`).join('')}</div>`;
  else if(tab==='photos'){const imgs=POSTS.filter(x=>x[3]);content=`<div class="wt-photo-grid">${imgs.map(x=>`<figure><img src="assets/photos/${x[3]}"><figcaption>${x[0]} · ${x[1]}</figcaption></figure>`).join('')}</div>`}
  else if(tab==='gear')content=`<div class="wt-gearlist"><section><h2>GPS / 导航</h2><p><b>Garmin GPSMAP 67i</b> · 2023至今</p><p>右上角外壳被摔裂一次；2025年换过挂绳。</p></section><section><h2>相机</h2><p><b>Sony RX100 VII</b> · 2024至今</p><p>不带第二块电池的原因：周野每次都说“够用”。</p></section><section><h2>背负</h2><p><b>65L背包</b> · 2021至今</p><p>肩带修补3次，腰带修补1次。</p></section><section><h2>旧设备</h2><p>2019年的头灯仍在装备库，但已经不建议夜线使用。</p></section></div>`;
  else content=`<div class="wt-about"><h2>关于周野</h2><p>2019年开始公开记录徒步与路线复核。不是职业向导，也不接商业带队。喜欢在路线结束以后把“走错路”改称为“验证了另一条线”。</p><h3>常去地点</h3><p>南岭、帽山、虎峡、乌伦河公开步道。</p><h3>资料习惯</h3><p>原图通常放在Cloudline，路线先在本地改完再公开。遇到不确定的地点会把照片和轨迹分别保存，避免之后互相“证实”。</p></div>`;
  app.innerHTML=`<section class="wildtrace">${wildGlobalNav()}<div class="wt-cover"><img src="assets/photos/mist_ridge.webp"><div class="wt-user"><img src="assets/photos/profile_zhou.webp"><div><h1>周野 <small>Ye Zhou</small></h1><p>山会改路，照片也会过期。</p></div><dl><div><b>132</b><span>动态</span></div><div><b>48</b><span>路线</span></div><div><b>2.4k</b><span>关注者</span></div><div><b>316</b><span>关注</span></div></dl></div></div><nav class="wt-tabs">${tabs.map(t=>`<a class="${tab===t[0]?'active':''}" data-nav="wildtrace.app/u/zhou-ye?tab=${t[0]}">${t[1]}</a>`).join('')}</nav><main class="wt-profile-main">${content}<aside class="wt-aside"><h3>2026计划</h3><p>阿泽拉野外季<br>09.18—10.02</p><h3>公开收藏</h3><a data-nav="wildtrace.app/routes">乌伦河公开步道</a><a data-nav="wildtrace.app/routes">帽山旧林道</a><a data-nav="wildtrace.app/routes">西岭北脊</a><h3>最近访问</h3><a data-nav="azera-rainforest.org/season-2026">ACRP 2026 野外季</a></aside></main></section>`;
  bindWildSearch();
}
function bindWildSearch(){const q=$('#wtSearch');if(q)q.onkeydown=ev=>{if(ev.key==='Enter')nav('echosearch.net/search?q='+encodeURIComponent(ev.target.value.trim()+' site:wildtrace.app'))}}
function renderWildExplore(){app.innerHTML=`<section class="wildtrace simple-wild">${wildGlobalNav('explore')}<main><h1>探索</h1><p>附近公开路线、近期天气与社区记录。</p><div class="explore-grid"><article><img src="assets/photos/mist_ridge.webp"><h2>帽山旧林道</h2><p>18.4 km · 中等 · 雨季泥泞</p></article><article><img src="assets/photos/wet_gear.webp"><h2>乌伦河公开步道</h2><p>14.8 km · 中等 · 河口区域</p></article><article><img src="assets/photos/camp_river.webp"><h2>虎峡北线</h2><p>39.2 km · 困难 · 涉水</p></article></div></main></section>`;bindWildSearch()}
function renderWildRoutes(){app.innerHTML=`<section class="wildtrace simple-wild">${wildGlobalNav('routes')}<main><h1>路线库</h1><div class="route-directory">${ROUTES.map(r=>`<article><b>${r[1]}</b><span>${r[2]} · ${r[3]}</span><p>社区记录 · 最近更新 ${r[0]}</p></article>`).join('')}</div></main></section>`;bindWildSearch()}
function renderWildCommunity(){app.innerHTML=`<section class="wildtrace simple-wild">${wildGlobalNav('community')}<main><h1>社区</h1><div class="community-stream"><article><b>林澈</b><p>提醒一下：雨季涉水以后脚泡白了不是“正常户外感”，是该换干袜子。</p></article><article><b>陈栩</b><p>收一块老款无人机电池，别问为什么又是我。</p></article><article><b>周野</b><p>今年有人走过乌伦公开步道吗？想对一下第三支流河口有没有继续塌。</p><small>2026.08.02 · 14条回复</small></article></div></main></section>`;bindWildSearch()}
function renderWildGear(){app.innerHTML=`<section class="wildtrace simple-wild">${wildGlobalNav('gear')}<main><h1>装备讨论</h1><div class="gear-topics"><article><h2>GPSMAP 67i在峡谷里的漂移到底有多离谱？</h2><p>78条回复 · 最后回复 2小时前</p></article><article><h2>雨季五天，镜头布带几块才够</h2><p>31条回复 · 最后回复 昨天</p></article><article><h2>别再把无人机当营地吹风机</h2><p>陈栩 · 置顶笑话帖</p></article></div></main></section>`;bindWildSearch()}

function mapLine(points,cls){return `<polyline class="${cls}" points="${points.map(p=>`${Array.isArray(p)?p[0]:p.x},${Array.isArray(p)?p[1]:p.y}`).join(' ')}"/>`}
function renderMap(p){
  const g=st.gis; const visiblePts=MAP_DATA.actual.filter((_,i)=>i<=Math.floor(g.time/100*(MAP_DATA.actual.length-1)));
  app.innerHTML=`<section class="geoapp"><header class="geo-menubar"><b>GeoExplorer Pro <small>3.8</small></b><span>项目</span><span>地图</span><span>图层</span><span>分析</span><span>视图</span><span>帮助</span><div class="geo-search"><input id="geoSearch" placeholder="查找地点或坐标"></div></header><div class="geo-canvas" id="geoCanvas"><div class="geo-world" id="geoWorld" style="transform:translate(${g.tx}px,${g.ty}px) scale(${g.zoom})"><img src="assets/maps/ulen_dem.webp" class="dem"><img src="assets/maps/rain_0922.webp" class="rain-layer ${g.rain?'on':''}"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${g.planned?mapLine(MAP_DATA.planned,'route-plan'):''}${g.actual?mapLine(visiblePts,'route-actual'):''}${visiblePts.map((pt,i)=>`<circle data-trackpt="${i}" cx="${pt.x}" cy="${pt.y}" r=".55"/>`).join('')}${g.drone?'<rect x="67" y="61" width="14" height="11" class="drone-footprint"/><path d="M72 69 C76 72 80 77 84 82" class="old-channel"/>':''}${g.measure.length===2?`<line x1="${g.measure[0].x}" y1="${g.measure[0].y}" x2="${g.measure[1].x}" y2="${g.measure[1].y}" class="measure-line"/>`:''}</svg></div><div class="geo-crosshair" hidden>＋</div></div>
  <aside class="geo-layers"><header>图层 <button id="hideLayers">×</button></header><label><input id="lyPlan" type="checkbox" ${g.planned?'checked':''}> 计划路线 v3</label><label><input id="lyActual" type="checkbox" ${g.actual?'checked':''}> GPS原始轨迹</label><label><input id="lyRain" type="checkbox" ${g.rain?'checked':''}> 9/21—22累计降雨</label><label><input type="checkbox" checked disabled> 等高线 40m</label><label><input type="checkbox" checked disabled> 水系 / 旧河谷</label><label><input id="lyDrone" type="checkbox" ${g.drone?'checked':''}> 无人机临时标注</label></aside>
  <div class="geo-toolbar"><button id="zin" title="放大">＋</button><button id="zout" title="缩小">−</button><button id="homeMap" title="全图">⌂</button><button id="measure" class="${g.measureMode?'active':''}" title="测距">⌁</button></div>
  <aside class="geo-inspector"><header>对象检查器</header><div id="geoInspect"><p>点击GPS轨迹点查看时间、高程和记录精度。拖动地图可平移，滚轮缩放。</p></div><div class="elev-profile"><svg viewBox="0 0 260 72" preserveAspectRatio="none"><polyline points="${MAP_DATA.actual.map((x,i)=>`${i/(MAP_DATA.actual.length-1)*260},${68-(x.elev-270)/270*60}`).join(' ')}"/></svg><small>GPS高程剖面 · 09/21—22</small></div></aside>
  <div class="geo-time"><span>09/21 06:00</span><input id="geoTime" type="range" min="0" max="100" value="${g.time}"><span>09/22 18:00</span></div>
  <div class="geo-status"><span id="geoCoord">2.4175°N, 114.2260°E</span><span>EPSG:4326</span><span id="scaleText">1 km</span></div></section>`;
  bindMap();
}
function bindMap(){const g=st.gis,canvas=$('#geoCanvas'),world=$('#geoWorld');let drag=null;
  function commit(){save();renderMap(parseUrl())}
  $('#zin').onclick=()=>{g.zoom=Math.min(3.2,g.zoom*1.25);commit()}; $('#zout').onclick=()=>{g.zoom=Math.max(.75,g.zoom/1.25);commit()}; $('#homeMap').onclick=()=>{g.zoom=1;g.tx=0;g.ty=0;commit()};
  $('#lyPlan').onchange=e=>{g.planned=e.target.checked;save();renderMap(parseUrl())}; $('#lyActual').onchange=e=>{g.actual=e.target.checked;save();renderMap(parseUrl())};
  $('#lyRain').onchange=e=>{g.rain=e.target.checked;if(g.rain&&g.time>55)flag('gis_rain_seen');save();renderMap(parseUrl())}; $('#lyDrone').onchange=e=>{g.drone=e.target.checked;save();renderMap(parseUrl())};
  $('#measure').onclick=()=>{g.measureMode=!g.measureMode;g.measure=[];commit()};
  $('#geoTime').oninput=e=>{g.time=+e.target.value;save();if(g.rain&&g.time>55)flag('gis_rain_seen');renderMap(parseUrl())};
  canvas.onwheel=e=>{e.preventDefault();g.zoom=Math.max(.75,Math.min(3.2,g.zoom*(e.deltaY>0?.9:1.1)));save();world.style.transform=`translate(${g.tx}px,${g.ty}px) scale(${g.zoom})`;$('#scaleText').textContent=(1/g.zoom).toFixed(1)+' km'};
  canvas.onpointerdown=e=>{if(e.target.dataset.trackpt||g.measureMode)return;drag={x:e.clientX,y:e.clientY,tx:g.tx,ty:g.ty};canvas.setPointerCapture(e.pointerId)};
  canvas.onpointermove=e=>{const rect=canvas.getBoundingClientRect();const px=(e.clientX-rect.left)/rect.width*100,py=(e.clientY-rect.top)/rect.height*100;const lon=MAP_DATA.extent.west+(MAP_DATA.extent.east-MAP_DATA.extent.west)*px/100,lat=MAP_DATA.extent.north-(MAP_DATA.extent.north-MAP_DATA.extent.south)*py/100;$('#geoCoord').textContent=`${lat.toFixed(4)}°N, ${lon.toFixed(4)}°E`;if(drag){g.tx=drag.tx+e.clientX-drag.x;g.ty=drag.ty+e.clientY-drag.y;world.style.transform=`translate(${g.tx}px,${g.ty}px) scale(${g.zoom})`}};
  canvas.onpointerup=e=>{if(drag){drag=null;save()}if(g.measureMode&&!e.target.dataset.trackpt){const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*100,y=(e.clientY-rect.top)/rect.height*100;g.measure.push({x,y});if(g.measure.length>2)g.measure=[g.measure[1],{x,y}];save();renderMap(parseUrl())}};
  $$('[data-trackpt]').forEach(c=>c.onclick=ev=>{ev.stopPropagation();const i=+c.dataset.trackpt,pt=MAP_DATA.actual[i];g.selected.push(i);g.selected=[...new Set(g.selected)].slice(-4);if(g.selected.filter(x=>x>=4).length>=3&&g.planned&&g.actual){g.compared=true;flag('gis_offset_seen')}save();const west=MAP_DATA.extent.west+(MAP_DATA.extent.east-MAP_DATA.extent.west)*pt.x/100,north=MAP_DATA.extent.north-(MAP_DATA.extent.north-MAP_DATA.extent.south)*pt.y/100;$('#geoInspect').innerHTML=`<h2>GPS点 ${String(i+1).padStart(2,'0')}</h2><dl><dt>时间</dt><dd>${pt.time}</dd><dt>坐标</dt><dd>${north.toFixed(4)}N, ${west.toFixed(4)}E</dd><dt>GPS高程</dt><dd>${pt.elev} m</dd><dt>精度</dt><dd>± ${pt.acc} m</dd></dl><button id="pinPoint">复制坐标</button>`;$('#pinPoint').onclick=()=>navigator.clipboard?.writeText(`${north.toFixed(4)}N, ${west.toFixed(4)}E`).then(()=>toast('坐标已复制')).catch(()=>toast('坐标：'+north.toFixed(4)+'N, '+west.toFixed(4)+'E'))});
  $('#geoSearch').onkeydown=e=>{if(e.key==='Enter'){const v=e.target.value.trim();if(/114\.|2\./.test(v))toast('坐标已定位到当前项目范围');else toast('项目地图中未找到该名称')}};
}

function renderCloud(p){
  const view=p.query.get('view')||'photos'; const ghost=pollution()>=3; const list=[...CLOUD_PHOTOS];
  if(ghost)list.push({file:'horror_08.webp',time:'—',name:'IMG_0000_RECOVERED.JPG',cam:'未知',iso:'—',lens:'—',caption:'',ghost:true});
  let shown=list;if(view==='recent')shown=list.slice(-6);if(view==='shared')shown=list.filter((_,i)=>i%3===0);if(view==='trash')shown=[];
  app.innerHTML=`<section class="cloud-app"><aside class="cloud-side"><div class="cloud-logo">☁ Cloudline</div><nav><button class="${view==='photos'?'active':''}" data-nav="cloudline.app/shared/zhouye-field?view=photos">照片</button><button class="${view==='recent'?'active':''}" data-nav="cloudline.app/shared/zhouye-field?view=recent">最近添加</button><button class="${view==='shared'?'active':''}" data-nav="cloudline.app/shared/zhouye-field?view=shared">共享给我</button><button class="${view==='trash'?'active':''}" data-nav="cloudline.app/shared/zhouye-field?view=trash">已删除</button></nav><div class="album-label">相簿</div><button class="album active" data-nav="cloudline.app/shared/zhouye-field?view=photos">2026 · 阿泽拉 <span>${list.length}</span></button><button class="album" data-nav="wildtrace.app/u/zhou-ye?tab=photos">公开户外照片 <span>6</span></button><div class="cloud-owner">所有者<br><b>周野</b><small>${ghost?'最近活动 2分钟前':'最后同步 09/23 00:41'}</small></div></aside><main class="cloud-main"><header><div><h1>2026年9月</h1><span>${shown.length} 项</span></div><input id="cloudSearch" placeholder="搜索文件名、时间或设备"></header>${shown.length?`<div class="cloud-grid">${shown.map((ph,i)=>`<button class="cloud-photo ${ph.ghost?'ghost-photo':''}" data-cloud-index="${list.indexOf(ph)}" data-key="${esc((ph.name+' '+ph.time+' '+ph.cam).toLowerCase())}"><img src="assets/photos/${ph.file}" alt=""><time>${ph.time}</time></button>`).join('')}</div>`:'<div class="cloud-empty">没有项目</div>'}</main></section>`;
  $$('[data-cloud-index]').forEach(b=>b.onclick=()=>openCloudPhoto(list,+b.dataset.cloudIndex));
  $('#cloudSearch').oninput=ev=>{const q=ev.target.value.trim().toLowerCase();$$('.cloud-photo').forEach(el=>el.hidden=q&&!el.dataset.key.includes(q))};
}
function openCloudPhoto(list,i){const p=list[i]; if(!p)return; if(!st.openedPhotos.includes(p.name))st.openedPhotos.push(p.name);save(); if(p.file==='old_tree_gear.webp')flag('old_camera_seen');if(p.file==='horror_02.webp')flag('village_photo_seen');if(p.file==='classroom_wall.webp'||p.file==='ritual_platform.webp')flag('glyph_context_seen');if(p.ghost)flag('ghost_index');
  modal.innerHTML=`<div class="photo-view"><header><button class="pv-close">×</button><b>${p.name}</b><span>${p.time}</span></header><div class="photo-stage"><button class="pv-prev">‹</button><img src="assets/photos/${p.file}" alt="${esc(p.name)}"><button class="pv-next">›</button></div><aside><h2>EXIF 信息</h2><dl><dt>文件</dt><dd>${p.name}</dd><dt>拍摄时间</dt><dd>${p.time}</dd><dt>设备</dt><dd>${p.cam}</dd><dt>ISO</dt><dd>${p.iso}</dd><dt>等效焦距</dt><dd>${p.lens}</dd><dt>同步状态</dt><dd>${p.ghost?'原始索引不存在':'低带宽同步完成'}</dd>${p.ghost?'<dt>修改时间</dt><dd>今天 03:47</dd>':''}</dl>${p.file==='old_tree_gear.webp'?'<p class="meta-note">图像识别：可能包含相机、GPS接收机、织物。自动识别未确认型号。</p>':''}</aside></div>`;
  $('.pv-close').onclick=()=>modal.innerHTML=''; $('.pv-prev').onclick=()=>openCloudPhoto(list,(i-1+list.length)%list.length);$('.pv-next').onclick=()=>openCloudPhoto(list,(i+1)%list.length);
}

function tokenize(q){return q.toLowerCase().replace(/site:[^\s]+/g,'').split(/[\s,，。\-_/]+/).filter(Boolean)}
function searchDocs(q,tab='all'){
  const siteMatch=q.match(/site:([^\s]+)/i);const site=siteMatch?.[1]?.toLowerCase();const terms=tokenize(q);
  let docs=WEB_DOCS.filter(d=>!site||d.url.toLowerCase().includes(site));
  const tabKinds={news:['news','government'],forum:['forum','blog'],academic:['academic','archive'],docs:['manual','government','archive'],all:null};if(tabKinds[tab])docs=docs.filter(d=>tabKinds[tab].includes(d.kind));
  const score=d=>{const title=(d.title+' '+d.keys.join(' ')).toLowerCase(),all=(title+' '+d.snippet+' '+d.body.join(' ')).toLowerCase();let s=0;for(const t of terms){if(title.includes(t))s+=8;if(d.keys.some(k=>k.toLowerCase().includes(t)))s+=7;if(all.includes(t))s+=2}return s+(d.truth==='irrelevant'?.1:0)};
  return docs.map(d=>[score(d),d]).filter(x=>terms.length===0||x[0]>0).sort((a,b)=>b[0]-a[0]||b[1].date.localeCompare(a[1].date)).map(x=>x[1]);
}
function renderSearch(p){
  const q=p.query.get('q')||'';const tab=p.query.get('tab')||'all';const docs=q?searchDocs(q,tab):[];const tabs=[['all','全部'],['news','新闻'],['forum','论坛与博客'],['academic','学术'],['docs','文档']];
  let history=[...st.searchHistory];if(pollution()>=3&&!history.includes('口 身体 声音 amokha'))history.push('口 身体 声音 amokha');
  app.innerHTML=`<section class="echo"><header class="echo-head"><button class="echo-brand" data-nav="echosearch.net/search">EchoSearch</button><div class="echo-box"><input id="echoQ" value="${esc(q)}" placeholder="搜索互联网"><button id="echoGo">⌕</button></div><nav>${tabs.map(t=>`<a class="${tab===t[0]?'active':''}" data-nav="echosearch.net/search?q=${encodeURIComponent(q)}&tab=${t[0]}">${t[1]}</a>`).join('')}</nav></header><main class="echo-main">${q?`<div class="echo-count">约 ${Math.max(73,docs.length*947+q.length*212)} 条结果（本地离线镜像仅显示可访问页面）</div>${docs.length?docs.slice(0,18).map(d=>searchResult(d)).join(''):'<div class="no-results">没有找到与这些关键词完全匹配的已缓存页面。换一种写法可能会有结果。</div>'}`:`<section class="echo-home"><h1>搜索互联网</h1><p>索引包含公开网页、旧网页镜像和学术缓存。来源之间可能互相矛盾。</p>${history.length?`<h2>最近搜索</h2>${[...history].reverse().slice(0,10).map(x=>`<button data-nav="echosearch.net/search?q=${encodeURIComponent(x)}">${esc(x)}</button>`).join('')}`:''}</section>`}</main></section>`;
  const doSearch=()=>{const v=$('#echoQ').value.trim();if(!v)return;if(!st.searchHistory.includes(v))st.searchHistory.push(v);st.searchHistory=st.searchHistory.slice(-20);save();nav(`echosearch.net/search?q=${encodeURIComponent(v)}&tab=${tab}`)};$('#echoGo').onclick=doSearch;$('#echoQ').onkeydown=e=>{if(e.key==='Enter')doSearch()};
}
function searchResult(d){const host=new URL('https://'+d.url).host;return `<article class="echo-result"><div class="result-source"><span>${host[0].toUpperCase()}</span><div><b>${esc(d.source)}</b><small>${esc(d.url)}</small></div></div><h2><a data-nav="${esc(d.url)}">${esc(d.title)}</a></h2><p>${esc(d.snippet)}</p><time>${d.date}</time></article>`}

function renderWebDoc(d,p){
  if(!st.openedDocs.includes(d.id))st.openedDocs.push(d.id);save(); if(['familyblog','sar2011','news2011'].includes(d.id))flag('camera_history_read');if(d.id==='water_report'||d.id==='weather')flag('hydrology_read');if(d.id==='fieldnote')flag('fieldnote_read');if(d.id==='eru')flag('painter_read');
  if(d.kind==='news'||d.kind==='tabloid')return renderNewsDoc(d);
  if(d.kind==='forum')return renderForumDoc(d);
  if(d.kind==='academic')return renderAcademicDoc(d);
  if(d.kind==='government')return renderGovDoc(d);
  if(d.kind==='archive')return renderArchiveDoc(d);
  if(d.kind==='manual')return renderManualDoc(d);
  if(d.kind==='blog')return renderBlogDoc(d);
  if(d.kind==='commercial')return renderCommercialDoc(d);
  renderBlogDoc(d);
}
function docParas(d){return d.body.map(x=>`<p>${x}</p>`).join('')}
function relatedDocs(d){const rel=WEB_DOCS.filter(x=>x!==d&&x.keys.some(k=>d.keys.includes(k))).slice(0,4);return rel.map(x=>`<a data-nav="${x.url}">${x.title}<small>${x.source}</small></a>`).join('')}
function renderNewsDoc(d){const sensational=d.kind==='tabloid';app.innerHTML=`<section class="newsdoc ${sensational?'sensational':''}"><header><b>${d.source}</b><nav>首页　${sensational?'奇闻　未解':'本地　社会　环境　档案'}</nav><input placeholder="站内搜索"></header><main><article><div class="crumb">${sensational?'未解 / 雨林':'地方 / 搜救档案'}</div><h1>${d.title}</h1><div class="byline">${d.date} · 编辑部整理</div><div class="news-body">${docParas(d)}</div><footer>本文页面来自公开网页离线镜像。原站评论未完整保存。</footer></article><aside><h3>相关报道</h3>${relatedDocs(d)}</aside></main></section>`}
function renderForumDoc(d){app.innerHTML=`<section class="forumdoc"><header><b>${d.source}</b><input placeholder="搜索论坛"><span>登录　注册</span></header><div class="forum-crumb">论坛首页 › 户外路线 › 乌伦上游</div><main><h1>${d.title}</h1>${d.body.map((x,i)=>`<article><aside><b>${i?'riverwalker_'+(14+i*23):'楼主'}</b><small>注册 ${2010+i}年</small></aside><div><time>${d.date} ${10+i}:2${i}</time><p>${x}</p></div></article>`).join('')}</main></section>`}
function renderAcademicDoc(d){app.innerHTML=`<section class="academicdoc"><header><b>OpenField Journals</b><nav>Journals　Browse　Metrics　About</nav></header><main><div class="journal">${d.source}</div><h1>${d.title}</h1><p class="authors">Research article · ${d.date}</p><section class="abstract"><h2>Abstract</h2>${docParas(d)}</section><aside><b>Citation</b><p>Cached HTML version. Figures and supplementary files may be incomplete.</p></aside></main></section>`}
function renderGovDoc(d){app.innerHTML=`<section class="govdoc"><header><div class="govseal">A</div><div><b>${d.source}</b><small>公开信息服务</small></div><nav>首页　信息公开　历史资料　联系我们</nav></header><main><div class="gov-path">信息公开 › 历史资料</div><h1>${d.title}</h1><div class="gov-meta">发布日期：${d.date}　来源：${d.source}</div>${docParas(d)}<div class="gov-stamp">公开版 / 部分附件不提供在线访问</div></main></section>`}
function renderArchiveDoc(d){
  const isEru=d.id==='eru'; const isField=d.id==='fieldnote';
  app.innerHTML=`<section class="archivedoc"><header><b>雨林大学数字馆藏</b><span>Special Collections / Field Anthropology</span><input placeholder="检索馆藏"></header><main><aside><b>馆藏编号</b><p>${isEru?'UL-1978-19/A7':'UL-1978-19'}</p><b>年代</b><p>${d.date}</p><b>访问状态</b><p>研究开放 · 数字化不完整</p><a data-nav="archive.rainforest-u.edu/anthro/UL-index">查看同组索引</a></aside><article><div class="archive-label">未出版材料</div><h1>${d.title}</h1>${docParas(d)}${isField?`<div class="glyph-fragment"><p>页边重复的字形：</p>${glyph('body')}${glyph('name')}${glyph('river')}${glyph('rain')}${glyph('dream')}<small>记录者注：“不要建立一一对应词典。方向缺口可能改变关系，而不是时态。”</small></div><p><a data-nav="archive.rainforest-u.edu/anthro/UL-1978-19/A7">附页A7：肖像练习（长期误标）</a></p>`:''}${isEru?`<div class="eru-sequence">${[1,2,3,4,5].map((n,i)=>`<figure><img src="assets/photos/sena_${n}.webp"><figcaption>${['今天还记得她把头发扎在右边。','她笑的时候左边嘴角先动。','昨天想不起她手背上的痣在哪边。','今天画眼睛用了三次。','今天已经画不像她了。'][i]}</figcaption></figure>`).join('')}</div><blockquote>“如果一个人只能在肉里留下，为什么还要教孩子写名字？”</blockquote>`:''}</article></main></section>`;
}
function renderManualDoc(d){app.innerHTML=`<section class="manualdoc"><header>TECH REFERENCE LIBRARY</header><div class="manual-layout"><nav><b>产品资料</b><span>规格</span><span>电池</span><span>存储介质</span><span>常见故障</span></nav><main><div class="manual-path">Digital Camera / Archive</div><h1>${d.title}</h1>${docParas(d)}<table><tr><th>发布年代</th><td>2009</td></tr><tr><th>电池</th><td>NP-BG1 / NP-FG1</td></tr><tr><th>存储</th><td>Memory Stick Duo</td></tr></table></main></div></section>`}
function renderBlogDoc(d){app.innerHTML=`<section class="blogdoc"><header><b>${d.source}</b><span>记录路线、语言和偶尔不可靠的记忆。</span></header><main><article><time>${d.date}</time><h1>${d.title}</h1>${docParas(d)}<footer>标签：${d.keys.slice(0,4).join(' / ')}</footer></article><aside><h3>归档</h3><span>2026</span><span>2024</span><span>2019</span><h3>相关</h3>${relatedDocs(d)}</aside></main></section>`}
function renderCommercialDoc(d){app.innerHTML=`<section class="commercialdoc"><header><b>${d.source}</b><nav>路线　住宿　攻略　预订</nav></header><div class="commercial-hero text-only"><h1>${d.title}</h1><p>Rain-season trekking / cached itinerary</p></div><main>${docParas(d)}<p class="cache-warning">页面为旧缓存；原站预订模块未被镜像保存。</p></main></section>`}

function renderMedical(p){
  const tab=p.query.get('tab')||'daily';
  const tabs=[['daily','每日记录'],['stats','症状统计'],['meds','药品清单'],['labs','检测结果']];
  let content='';
  const rows=[['09/20','林澈','37.4','82','118/76','头痛、恶心','观察','林澈'],['09/20','高桥健','36.8','76','110/70','疲惫、食欲下降','补液','林澈'],['09/20','陈栩','37.5','88','122/80','无明显症状','—','林澈'],['09/21','周野','37.1','96','126/82','轻微喉咙痛','观察','林澈'],['09/21','王敬山','37.6','92','124/78','轻度恶心','补液','林澈'],['09/22','王敬山','38.4','118','134/90','恶心、反复呕吐','口服补液','林澈'],['09/22','许放','37.9','104','126/84','眩晕、厌恶气味','观察','林澈'],['09/22','高桥健','38.3','112','132/86','高热、短暂定向混乱','退热','林澈'],['09/23','林澈','—','—','—','本人未记录','—','最后同步不完整']];
  if(tab==='daily')content=`<div class="sheet-grid"><table><thead><tr><th>#</th><th>日期</th><th>姓名</th><th>体温°C</th><th>心率</th><th>血压</th><th>主诉/症状</th><th>处理</th><th>记录者</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><th>${i+2}</th>${r.map((x,j)=>`<td class="${i>=5&&j===2?'warncell':''} ${i===7&&j===6?'has-comment':''}" ${i===7&&j===6?'data-med-comment="1"':''}>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  if(tab==='stats')content=`<div class="sheet-grid"><table><thead><tr><th>日期</th><th>记录人数</th><th>发热≥38</th><th>恶心/呕吐</th><th>定向异常</th><th>备注</th></tr></thead><tbody><tr><td>09/20</td><td>3</td><td>0</td><td>1</td><td>0</td><td>正常野外波动</td></tr><tr><td>09/21</td><td>2</td><td>0</td><td>1</td><td>0</td><td>持续观察</td></tr><tr><td>09/22</td><td>3</td><td>2</td><td>2</td><td>1</td><td>停用交换食物</td></tr></tbody></table></div>`;
  if(tab==='meds')content=`<div class="sheet-grid"><table><thead><tr><th>物品</th><th>出发数量</th><th>09/22余量</th><th>储存</th><th>备注</th></tr></thead><tbody><tr><td>对乙酰氨基酚</td><td>24</td><td>14</td><td>医疗包A</td><td>正常</td></tr><tr><td>口服补液盐</td><td>24</td><td>18</td><td>医疗包A</td><td>正常</td></tr><tr><td>碘伏棉签</td><td>60</td><td>41</td><td>医疗包B</td><td>正常</td></tr><tr><td>快速检测试纸</td><td>10</td><td>8</td><td>干燥袋</td><td>未发现阳性</td></tr></tbody></table></div>`;
  if(tab==='labs')content=`<div class="sheet-grid"><table><thead><tr><th>样本</th><th>日期</th><th>项目</th><th>结果</th><th>解释</th></tr></thead><tbody><tr><td>WJ-0921-01</td><td>09/21</td><td>饮水余氯</td><td>合格</td><td>营地封装水</td></tr><tr><td>FD-0922-02</td><td>09/22</td><td>交换食物留样</td><td>未完成</td><td>样本量不足</td></tr><tr><td>KT-0922</td><td>09/22</td><td>快速感染筛查</td><td>阴性</td><td>不能排除其他原因</td></tr></tbody></table></div>`;
  app.innerHTML=`<section class="sheet-app"><header class="sheet-title"><span class="sheet-icon">▦</span><b>阿泽拉联合项目 — 现场医疗记录（内部）.xlsx</b><small>最后保存：2026-09-23 01:17</small></header><nav class="sheet-menu"><button data-sheetmenu="file">文件</button><button data-sheetmenu="edit">编辑</button><button data-sheetmenu="view">查看</button><button data-sheetmenu="insert">插入</button><button data-sheetmenu="data">数据</button><button data-sheetmenu="tools">工具</button></nav><div class="formula-bar"><span>fx</span><input value="${tab==='daily'?'=记录表!A1:I10':'='+tab.toUpperCase()+'!A1:F20'}" readonly></div>${content}<nav class="sheet-tabs">${tabs.map(t=>`<button class="${tab===t[0]?'active':''}" data-nav="docs.azera-research.org/medical-log?tab=${t[0]}">${t[1]}</button>`).join('')}<span>＋</span></nav><div id="sheetPopover"></div></section>`;
  $$('[data-med-comment]').forEach(el=>el.onclick=()=>openMedicalComment());$$('[data-sheetmenu]').forEach(b=>b.onclick=()=>sheetMenu(b.dataset.sheetmenu));
}
function openMedicalComment(){flag('medical_comment_read');$('#sheetPopover').innerHTML=`<div class="sheet-comment"><header>批注 · 林澈 <button id="closeComment">×</button></header><p>高桥醒过一阵，说Nema一直给他换额头上的湿布。他问我“她是不是参与那个仪式的人”。我说我不知道，也没必要现在知道。</p><p>他后来坚持把之前的译法划掉：Nema对“留下”这个词的用法，和我们一直理解的“处理尸体”并不是一回事。至少不能写成等号。</p><time>09/23 00:18</time></div>`;$('#closeComment').onclick=()=>$('#sheetPopover').innerHTML=''}
function sheetMenu(kind){const text={file:'只读事故保全副本。可导出当前工作表，但不能覆盖原文件。',edit:'事故保全副本禁止编辑。复制与查找仍可用。',view:'当前视图：网格线、冻结首行、显示批注标记。',insert:'只读副本不能新增行、列或批注。',data:'原文件按日期升序保存，没有自动删除异常值。',tools:'版本历史：09/22 21:44、09/23 00:18、09/23 01:17。'}[kind];toast(text)}

const DRONE_FRAMES=[
  {file:'rit_04.webp',time:'09/21 13:31:08',name:'SORTIE_0921_WEST_001.JPG',alt:'338 m',note:'西岸河谷总览'},
  {file:'rit_05.webp',time:'09/22 13:33:42',name:'DJI_0508_PROXY_014.JPG',alt:'312 m',note:'屋顶区代理帧'},
  {file:'rit_07.webp',time:'09/22 13:34:05',name:'DJI_0508_PROXY_019.JPG',alt:'309 m',note:'中央空地代理帧'},
  {file:'rit_08.webp',time:'09/22 13:36:27',name:'DJI_0508_PROXY_033.JPG',alt:'296 m',note:'旧河槽附近'}
];
function renderDrone(p){const i=Math.max(0,Math.min(DRONE_FRAMES.length-1,+(p.query.get('f')||0))),f=DRONE_FRAMES[i];if(i===1)flag('drone_village_seen');if(i===3)flag('oldriver_seen');
  app.innerHTML=`<section class="survey"><header><b>Survey Review</b><span>ARZ / UL09 / 2026-09-22</span><nav>代理帧序列 · 原视频未完成同步</nav></header><aside class="survey-files"><h2>恢复队列</h2>${DRONE_FRAMES.map((x,n)=>`<button class="${i===n?'active':''}" data-nav="survey.azera-research.org/review/0922?f=${n}"><b>${x.name}</b><small>${x.time}</small></button>`).join('')}<hr><div class="queue"><b>原文件状态</b><p>DJI_0508.MP4<br>23:46 · 642 MB<br><span>未完成</span></p><p>当前只恢复JPEG代理帧，不伪装成可播放视频。</p></div></aside><main class="survey-stage"><img src="assets/photos/${f.file}"><div class="hud top">UL-09 / JPEG PROXY<br>${f.time}</div><div class="hud bottom">ALT ${f.alt}　GNSS ±7m</div><div class="frame-control"><button id="prevFrame">◀</button><span>${i+1} / ${DRONE_FRAMES.length}</span><button id="nextFrame">▶</button></div></main><aside class="survey-meta"><h2>${f.name}</h2><dl><dt>任务</dt><dd>0922 西岸低空复核</dd><dt>时间</dt><dd>${f.time}</dd><dt>高程</dt><dd>${f.alt}</dd><dt>来源</dt><dd>卫星箱低清代理</dd><dt>原片</dt><dd>恢复未完成</dd></dl><p>${f.note}</p><button id="openGisAt">在项目GIS打开该区域</button></aside></section>`;
  $('#prevFrame').onclick=()=>nav(`survey.azera-research.org/review/0922?f=${Math.max(0,i-1)}`);$('#nextFrame').onclick=()=>nav(`survey.azera-research.org/review/0922?f=${Math.min(DRONE_FRAMES.length-1,i+1)}`);$('#openGisAt').onclick=()=>{st.gis.drone=true;save();nav('atlas.azera-research.org/project/UL09')};
}

const OLD_MAP=[
'####################','#......~~~~~........#','#..##..~~~~..####...#','#......~~~~......#..#','#.####.....#####.#..#','#......##........#..#','#.####....#####.....#','#....#..............#','#....#.######.######','#.................G#','####################'];
function renderOldSite(p){const page=p.path.split('/').filter(Boolean)[0]||'home';st.flash.oldPage=page;save();const navs=[['home','首页'],['game','游戏'],['map','地图'],['fragments','碎片'],['guestbook','留言簿'],['links','友情链接']];let body='';
  if(page==='home')body=`<h2>更新 / 2011.08.07</h2><p>把第三张地图的树线往西挪了一点。有人说河弯不像游戏，我知道。</p><p>这个东西最开始只是给朋友做的路线记忆练习。后来有些地方我已经分不清是从照片画的，还是自己补出来的。</p><img class="oldphoto" src="assets/photos/rit_06.webp"><p class="tiny">最晚更新：2011.08.07　版本：0.7</p>`;
  if(page==='game')body=`<h2>林线之外 v0.7</h2><div class="gameframe"><canvas id="oldGame" width="640" height="430"></canvas></div><p>方向键移动。走到最右下角的旧石门。</p>`;
  if(page==='map')body=`<h2>地图笔记</h2><div class="old-map-notes"><p>第三张图的蓝线不是河，是“雨后会出现的路”。</p><div class="legend-row">${glyph('rain')}<span>连续三天雨以后才画这个记号</span></div><div class="legend-row">${glyph('road')}<span>作者草图里总贴着小径</span></div><div class="legend-row">${glyph('home')}<span>营地点旁边的形状</span></div><div class="legend-row">${glyph('return')}<span>这个我一直没弄懂，像折回去的箭头</span></div></div>`;
  if(page==='fragments')body=`<h2>碎片</h2><p>不是翻译，只是我把同一个符号出现的位置抄在一起。</p><table class="oldtable"><tr><th>位置</th><th>符号</th><th>旁边有什么</th></tr><tr><td>河滩石头</td><td>${glyph('rain')}</td><td>雨线 / 水痕</td></tr><tr><td>旧猎径</td><td>${glyph('road')}</td><td>分叉路</td></tr><tr><td>屋门内侧</td><td>${glyph('home','right')}</td><td>饭碗 / 儿童写字</td></tr><tr><td>旧路标背面</td><td>${glyph('return','left')}</td><td>反向箭头</td></tr></table><p class="tiny">“缺口朝向可能比主体更重要。”——我自己写的，别当真的。</p>`;
  if(page==='guestbook')body=`<h2>留言簿</h2><div class="guest"><b>2011/07/13 · riverbend</b><p>第三张图右边是不是死路？</p></div><div class="guest"><b>2011/07/19 · fqi7134</b><p>不是死路。你把雨天那条线和旧路叠一下。</p></div><div class="guest"><b>2011/08/02 · anonymous</b><p>你把现实坐标画进去了？</p></div><div class="guest"><b>2011/08/07 · admin</b><p>没坐标。只是记得河怎么弯。</p></div>`;
  if(page==='links')body=`<h2>友情链接</h2><ul class="oldlinks"><li><a data-nav="oldridge-notes.net/archive">个人登山记录（已失效）</a></li><li><a data-nav="camera-db.net/sony/dsc-w220">旧相机资料库</a></li><li><a data-nav="ulen-paddling.info/notes">Ulen River Paddling Notes（404）</a></li><li><a data-nav="trailtalk.asia/t/22184">TrailTalk旧帖</a></li></ul>`;
  app.innerHTML=`<section class="old-browser"><div class="old-window"><header><b>The Line Beyond / 林线之外</b><span>Last update 2011.08.07 · Visitors: 043172</span></header><nav>${navs.map(n=>`<a class="${page===n[0]?'active':''}" data-nav="linebeyond.net/${n[0]}">${n[1]}</a>`).join('')}</nav><div class="old-layout"><aside><div class="ascii">╔═══╗<br>║ ◇ ║<br>╚═╦═╝</div><p>一个关于走不出去的路的东西。</p><hr><small>IE8 / Firefox 3<br>1024×768 recommended</small></aside><main>${body}</main></div></div></section>`; if(page==='game')initOldGame();
}
function initOldGame(){const cv=$('#oldGame');if(!cv)return;const ctx=cv.getContext('2d');const cw=32,ch=39;function draw(){ctx.fillStyle='#030805';ctx.fillRect(0,0,640,430);for(let y=0;y<OLD_MAP.length;y++)for(let x=0;x<OLD_MAP[y].length;x++){const c=OLD_MAP[y][x];if(c==='#'){ctx.fillStyle='#143126';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}else if(c==='~'){ctx.fillStyle='#0d3640';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}else if(c==='G'){ctx.fillStyle='#6d1e18';ctx.fillRect(x*cw,y*ch,cw-1,ch-1)}}ctx.fillStyle='#dedcc4';ctx.fillRect(st.flash.x*cw+10,st.flash.y*ch+10,12,20);ctx.fillStyle='#82b69c';ctx.font='12px monospace';ctx.fillText('ARROWS',12,18)}draw();cv.tabIndex=0;cv.focus();cv.onkeydown=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();const nx=st.flash.x+d[0],ny=st.flash.y+d[1],c=OLD_MAP[ny]?.[nx];if(c&&c!=='#'&&c!=='~'){st.flash.x=nx;st.flash.y=ny;save();if(c==='G'&&!st.flash.gate)return openOldGate();draw()}}}
function openOldGate(){const choices=['rain','road','return','home','eye','body','river','name'];let seq=[];modal.innerHTML=`<div class="old-puzzle"><button class="close">×</button><h2>旧石门</h2><p>四个凹槽磨得很深。上方没有文字，只有从左到右四种痕迹：水痕、被鞋磨亮的细沟、一个折回去的箭头，以及门框一样的方形刻痕。</p><div class="stone-slots" id="stoneSlots"></div><div class="stone-choices">${choices.map(k=>`<button data-stone="${k}">${glyph(k)}</button>`).join('')}</div><button id="stoneClear">擦掉</button><button id="stoneTry">按下石板</button><p id="stoneMsg"></p></div>`;const draw=()=>$('#stoneSlots').innerHTML=seq.map(k=>glyph(k)).join('');$$('[data-stone]').forEach(b=>b.onclick=()=>{if(seq.length<4){seq.push(b.dataset.stone);draw()}});$('#stoneClear').onclick=()=>{seq=[];draw()};$('#stoneTry').onclick=()=>{if(seq.join(',')==='rain,road,return,home'){st.flash.gate=true;flag('oldgame_gate');modal.innerHTML='';toast('石门后的隐藏地图被保存到浏览器缓存')}else $('#stoneMsg').textContent='石板没有动。'};$('.old-puzzle .close').onclick=()=>modal.innerHTML=''}

function renderNotes(){const tab=pSafeQuery('tab')||'notes';const keys=Object.keys(GLYPHS);app.innerHTML=`<section class="notes-app"><header><b>本地笔记</b><nav><button class="${tab==='notes'?'active':''}" data-nav="fieldnotes.local?tab=notes">文字</button><button class="${tab==='glyphs'?'active':''}" data-nav="fieldnotes.local?tab=glyphs">符号草记</button></nav><span>仅保存在此设备</span></header>${tab==='notes'?`<main class="notes-paper"><textarea id="notesArea" placeholder="名字、坐标、矛盾的来源、你自己的判断……">${esc(st.notes)}</textarea></main>`:`<main class="glyph-notes">${keys.map(k=>`<div><span>${glyph(k)}</span><input data-glyphnote="${k}" value="${esc(st.glyphNotes[k]||'')}" placeholder="你的理解"></div>`).join('')}</main>`}</section>`;if($('#notesArea'))$('#notesArea').oninput=e=>{st.notes=e.target.value;save()};$$('[data-glyphnote]').forEach(i=>i.oninput=e=>{st.glyphNotes[i.dataset.glyphnote]=e.target.value;save()})}
function pSafeQuery(k){return parseUrl().query.get(k)}

function renderSatCache(p){if(!has('cache_recovered')){app.innerHTML=`<section class="cache-terminal"><header>ARZ-04 CACHE RECOVERY</header><main><h1>缓存恢复进行中</h1><p>当前访客权限只能查看已经完成校验的对象。</p><pre>OBJECT 0001…0344  OK\nOBJECT 0345…0381  VERIFYING\nTEXT FRAGMENTS      PENDING</pre></main></section>`;return}flag('last_log');app.innerHTML=`<section class="cache-terminal"><header>ARZ-04 CACHE RECOVERY / READ ONLY</header><main><div class="cache-meta">device ARZ-04 · local object 0382 · created 2026-09-23 02:41 · upload incomplete</div><h1>未完成上传的本地文本</h1><div class="cache-text"><p>我已经不知道今天到底算第几天。外面一直有人走，但不是所有人都在守着我们。</p><p>高桥昨天终于把那几个词拆开。他说我们把他们理解成“吃人”太简单。肉只是很多种留下人的方法之一，而且是最老、最有权力的一种。Nema给林澈换了一夜湿布，天亮以后又去参加了老人家的留身礼。在她那里，这两件事根本不冲突。</p><p>Tao把陈栩的相机摔了。他不想让我们拍孩子，也不想让我们“留下”。高桥说他的理由不是讨厌我们，而是怕陌生人的梦进到孩子身体里。我第一次听懂以后反而更不知道该怎么写。</p><p>有个叫Iri的小女孩问林澈：“你死以后，你家里的人会吃你吗？”林澈说不会。她想了很久，又问：“那他们怎么记得你？”</p><p>画画的人昨晚把一块电池和折起来的纸塞到旧河槽。他不会我们的语言，只指自己画的那个女人，再指脑袋。高桥说他大概是在说：记住不一定要把东西放进身体。</p><p>他把路标的缺口刻反了。许放一开始说那是错的，后来我们对地形才发现，按“错”的方向走会回到旧河道；按传统标记的方向才会进中央空地。</p><p>如果你看到这个，不要来找我。把地图、无人机位置和旧河道交给搜救。别把这里写成一群疯子，那样现场的人会判断错。这里有人想把我们留下，也有人在帮我们走。</p><blockquote>我最怕的不是他们相信这些。我最怕的是，我开始理解他们为什么会相信。</blockquote></div></main></section>`}

function renderRescue(p){
  const path=p.path; if(path==='/history')return renderRescueHistory(); if(path.includes('/bulletin'))return renderEnding(); if(path.includes('/supplement'))return renderRescueForm();
  app.innerHTML=`<section class="sar-app"><header><div class="sar-seal">应</div><div><b>国家应急管理部 · 搜救协调系统</b><small>SEARCH AND RESCUE COORDINATION</small></div><nav><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ">案件概览</a><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ/supplement">补充材料</a><a data-nav="sar.azera.gov/history">历史案件</a></nav></header><main class="sar-case"><div class="case-no">EM-2026-0924-ARZ</div><h1>阿泽拉雨林科考队失联事件</h1><dl><dt>案件状态</dt><dd>现场搜救进行中</dd><dt>涉事人数</dt><dd>6</dd><dt>责任单位</dt><dd>阿泽拉县搜救协调组 / 雨林大学</dd><dt>公开区域</dt><dd>乌伦河第三支流及上游步道</dd></dl><section><h2>当前任务</h2><p>复核最后可信区域、天气与路线变化；不依据未经证实的网络传闻调整搜索方向。</p><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ/supplement">提交可复核补充材料 →</a></section></main></section>`}

function renderRescueHistory(){app.innerHTML=`<section class="sar-app"><header><div class="sar-seal">应</div><div><b>国家应急管理部 · 搜救协调系统</b><small>SEARCH AND RESCUE COORDINATION</small></div><nav><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ">案件概览</a><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ/supplement">补充材料</a><a class="active" data-nav="sar.azera.gov/history">历史案件</a></nav></header><main class="sar-case"><h1>历史案件</h1><table class="sar-history"><thead><tr><th>编号</th><th>年份</th><th>区域</th><th>结果</th></tr></thead><tbody><tr><td>UL-2011-44</td><td>2011</td><td>乌伦河上游</td><td>搜救终止 / 人员未找到</td></tr><tr><td>UL-2018-09</td><td>2018</td><td>第三支流入口</td><td>洪水孤立 / 4人获救</td></tr><tr><td>ARZ-2023-17</td><td>2023</td><td>西岸样区</td><td>无人机失联 / 无人员伤亡</td></tr></tbody></table><p class="sar-muted">历史案件只保留公开结论；原始坐标和个人资料按权限限制。</p></main></section>`}
function renderRescueForm(){app.innerHTML=`<section class="sar-app"><header><div class="sar-seal">应</div><div><b>国家应急管理部 · 搜救协调系统</b><small>SEARCH AND RESCUE COORDINATION</small></div><nav><a data-nav="sar.azera.gov/case/EM-2026-0924-ARZ">案件概览</a><a class="active" data-nav="sar.azera.gov/case/EM-2026-0924-ARZ/supplement">补充材料</a><a data-nav="sar.azera.gov/history">历史案件</a></nav></header><main class="sar-form"><div class="form-head"><span>案件 EM-2026-0924-ARZ</span><h1>新增补充材料</h1><p>只填写可以由现场人员复核的位置、来源和风险。对居民身份、宗教或犯罪性质的判断不作为路线依据。</p></div><form id="sarForm"><label><span>坐标 / 区域中心</span><input name="coord" placeholder="例：2.4175N, 114.226E"></label><label><span>来源组合</span><select name="basis"><option value="">请选择</option><option value="gps-rain">GPS原始轨迹 + 雨量/水位</option><option value="gps-chat">GPS原始轨迹 + 现场改线记录</option><option value="drone-chat">无人机旧河槽 + 现场改线记录</option></select></label><label><span>现场风险说明</span><textarea name="risk" placeholder="写明可以复核的事实，不要写无法验证的传闻。"></textarea></label><label><span>附件说明</span><textarea name="attach" placeholder="可填写你使用的页面、文件名或时间。"></textarea></label><div id="sarError"></div><button>提交材料</button></form></main></section>`;$('#sarForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),coord=(fd.get('coord')||'').trim(),basis=fd.get('basis'),risk=(fd.get('risk')||'').trim();if(!has('rescue_ready'))return $('#sarError').textContent='现有材料之间仍缺少独立交叉来源，系统将保存草稿但不发送。';if(!coord||!basis||risk.length<25)return $('#sarError').textContent='请补全坐标、来源组合，并提供至少25字风险说明。';st.submitted=true;save();nav('sar.azera.gov/case/EM-2026-0924-ARZ/bulletin')}}
function renderEnding(){app.innerHTML=`<section class="bulletin-page"><header><b>国家应急管理部</b><span>信息公开</span></header><main><div class="bulletin-no">2026-09-30 / 阶段性通报</div><h1>阿泽拉雨林科考队搜救行动阶段性通报</h1><p>搜救队在乌伦河旧河槽附近发现部分科考装备、临时避雨点与一部损坏的卫星终端。现场未发现完整营地。受持续降雨和地形影响，大范围搜索已转为重点区域复查。</p><p>有关当地居民点、仪式活动及失踪人员后续去向的信息仍在核实。公开通报不采纳无法由现场证据独立验证的网络材料。</p><p>搜救协调组将继续与家属、项目单位及地方社区保持联系。</p></main><div class="system-notice"><b>Cloudline</b><span>共享目录索引：${CLOUD_PHOTOS.length+1} 项</span><small>所有者：周野 · 活动时间 2分钟前</small></div></section>`}
function render404(p){app.innerHTML=`<section class="plain404"><h1>无法访问此页面</h1><p>${esc(p.raw)}</p><p>地址可能已失效，或者当前离线镜像没有保存它。</p><button data-nav="echosearch.net/search?q=${encodeURIComponent(p.host)}">搜索这个站点</button></section>`}

render();
